$content = Get-Content -Raw -Path "HavenDevTools/Localization/strings.json" -Encoding UTF8

$keys = @{
    "azrael.almanac.refresh" = @{ da='Opdater alle'; de='Alle aktualisieren'; es='Actualizar todo'; fr='Tout actualiser'; it='Aggiorna tutto'; ja='すべて更新'; ko='모두 새로고침'; nl='Alles vernieuwen'; pt='Atualizar tudo'; 'pt-BR'='Atualizar tudo'; ru='Обновить всё'; sv='Uppdatera alla'; 'zh-CN'='全部刷新'; 'zh-TW'='全部重新整理'; uk='Оновити все' }
    "azrael.almanac.title" = @{ da='Havens Almanak'; de='Havens Almanach'; es='Almanaque de Haven'; fr='Almanach de Haven'; it='Almanacco di Haven'; ja='Havenのアルマナック'; ko='Haven의 앨머넥'; nl='Haven\u0027s Almanak'; pt='Almanaque de Haven'; 'pt-BR'='Almanaque de Haven'; ru='Альманах Haven'; sv='Havens Almanacka'; 'zh-CN'='Haven年鉴'; 'zh-TW'='Haven年鑑'; uk='Альманах Haven' }
    "azrael.birthday.check" = @{ da='Tjek fødselsdage'; de='Geburtstage prüfen'; es='Verificar cumpleaños'; fr='Vérifier les anniversaires'; it='Controlla compleanni'; ja='誕生日を確認'; ko='생일 확인'; nl='Verjaardagen controleren'; pt='Verificar aniversários'; 'pt-BR'='Verificar aniversários'; ru='Проверить дни рождения'; sv='Kontrollera födelsedagar'; 'zh-CN'='检查生日'; 'zh-TW'='檢查生日'; uk='Перевірити дні народження' }
    "azrael.birthday.refresh" = @{ da='Manuel opdatering'; de='Manuelle Aktualisierung'; es='Actualización manual'; fr='Actualisation manuelle'; it='Aggiornamento manuale'; ja='手動更新'; ko='수동 새로고침'; nl='Handmatig vernieuwen'; pt='Atualização manual'; 'pt-BR'='Atualização manual'; ru='Ручное обновление'; sv='Manuell uppdatering'; 'zh-CN'='手动刷新'; 'zh-TW'='手動重新整理'; uk='Ручне оновлення' }
    "azrael.birthday.test_notify" = @{ da='Send alle testmeddelelser'; de='Alle Testbenachrichtigungen senden'; es='Enviar todas las notificaciones de prueba'; fr='Envoyer toutes les notifications de test'; it='Invia tutte le notifiche di test'; ja='すべてのテスト通知を送信'; ko='모든 테스트 알림 본내기'; nl='Alle testmeldingen verzenden'; pt='Enviar todas as notificações de teste'; 'pt-BR'='Enviar todas as notificações de teste'; ru='Отправить все тестовые уведомления'; sv='Skicka alla testaviseringar'; 'zh-CN'='发送所有测试通知'; 'zh-TW'='發送所有測試通知'; uk='Надіслати всі тестові сповіщення' }
    "azrael.birthday.title" = @{ da='Fødselsdagspåmindelse'; de='Geburtstagserinnerung'; es='Recordatorio de cumpleaños'; fr='Rappel d\u0027anniversaire'; it='Promemoria compleanno'; ja='誕生日リマインダー'; ko='생일 알림'; nl='Verjaardagsherinnering'; pt='Lembrete de aniversário'; 'pt-BR'='Lembrete de aniversário'; ru='Напоминание о дне рождения'; sv='Födelsedagspåminnelse'; 'zh-CN'='生日提醒'; 'zh-TW'='生日提醒'; uk='Нагадування про день народження' }
    "azrael.birthright.active_bonuses" = @{ da='Aktive bonusser:'; de='Aktive Boni:'; es='Bonificaciones activas:'; fr='Bonus actifs :'; it='Bonus attivi:'; ja='アクティブなボーナス:'; ko='활성 복변스:'; nl='Actieve bonussen:'; pt='Bónus ativos:'; 'pt-BR'='Bônus ativos:'; ru='Активные бонусы:'; sv='Aktiva bonusar:'; 'zh-CN'='激活的加成：'; 'zh-TW'='激活的加成：'; uk='Активні бонуси:' }
    "azrael.birthright.title" = @{ da='Havens Birthright - Race Modifier Tracker'; de='Havens Birthright - Rassenmodifikator-Tracker'; es='Birthright de Haven - Rastreador de modificadores de raza'; fr='Birthright de Haven - Traqueur de modificateurs de race'; it='Birthright di Haven - Tracciatore modificatori razza'; ja='Haven\u0027s Birthright - 種族修正トラッカー'; ko='Haven의 Birthright - 종족 수정 추적기'; nl='Haven\u0027s Birthright - Rasmodificatie-tracker'; pt='Birthright de Haven - Rastreador de Modificadores de Raça'; 'pt-BR'='Birthright de Haven - Rastreador de Modificadores de Raça'; ru='Birthright Haven - Трекер расовых модификаторов'; sv='Havens Birthright - Rasmodifieringsspårare'; 'zh-CN'='Haven\u0027s Birthright - 种族修正追踪器'; 'zh-TW'='Haven\u0027s Birthright - 種族修正追蹤器'; uk='Birthright Haven - Трекер расових модифікаторів' }
    "azrael.none_detected" = @{ da='Ingen Azrael-mods registreret. Installer SenpaisChest, TheVault, S.M.U.T., Birthright, Birthday Reminder, Todo, Almanac eller Trinket Fortune.'; de='Keine Azrael-Mods erkannt. Installiere SenpaisChest, TheVault, S.M.U.T., Birthright, Birthday Reminder, Todo, Almanac oder Trinket Fortune.'; es='No se detectaron mods de Azrael. Instala SenpaisChest, TheVault, S.M.U.T., Birthright, Birthday Reminder, Todo, Almanac o Trinket Fortune.'; fr='Aucun mod d\u0027Azrael détecté. Installez SenpaisChest, TheVault, S.M.U.T., Birthright, Birthday Reminder, Todo, Almanac ou Trinket Fortune.'; it='Nessuna mod di Azrael rilevata. Installa SenpaisChest, TheVault, S.M.U.T., Birthright, Birthday Reminder, Todo, Almanac o Trinket Fortune.'; ja='AzraelのModが検出されませんでした。SenpaisChest、TheVault、S.M.U.T.、Birthright、Birthday Reminder、Todo、Almanac、Trinket Fortuneをインストールしてください。'; ko='Azrael의 모드가 감지되지 않았습니다. SenpaisChest, TheVault, S.M.U.T., Birthright, Birthday Reminder, Todo, Almanac 또는 Trinket Fortune을 설치하세요.'; nl='Geen Azrael-mods gedetecteerd. Installeer SenpaisChest, TheVault, S.M.U.T., Birthright, Birthday Reminder, Todo, Almanac of Trinket Fortune.'; pt='Nenhum mod do Azrael detetado. Instala o SenpaisChest, TheVault, S.M.U.T., Birthright, Birthday Reminder, Todo, Almanac ou Trinket Fortune.'; 'pt-BR'='Nenhum mod do Azrael detectado. Instale SenpaisChest, TheVault, S.M.U.T., Birthright, Birthday Reminder, Todo, Almanac ou Trinket Fortune.'; ru='Моды Azrael не обнаружены. Установите SenpaisChest, TheVault, S.M.U.T., Birthright, Birthday Reminder, Todo, Almanac или Trinket Fortune.'; sv='Inga Azrael-mods upptäckta. Installera SenpaisChest, TheVault, S.M.U.T., Birthright, Birthday Reminder, Todo, Almanac eller Trinket Fortune.'; 'zh-CN'='未检测到Azrael的模组。请安装SenpaisChest、TheVault、S.M.U.T.、Birthright、Birthday Reminder、Todo、Almanac或Trinket Fortune。'; 'zh-TW'='未偵測到Azrael的模組。請安裝SenpaisChest、TheVault、S.M.U.T.、Birthright、Birthday Reminder、Todo、Almanac或Trinket Fortune。'; uk='Моди Azrael не виявлено. Встановіть SenpaisChest, TheVault, S.M.U.T., Birthright, Birthday Reminder, Todo, Almanac або Trinket Fortune.' }
    "azrael.senpai.title" = @{ da='Senpais Kiste'; de='Senpais Truhe'; es='Cofre de Senpai'; fr='Coffre de Senpai'; it='Forziere di Senpai'; ja='Senpaiのチェスト'; ko='Senpai의 상자'; nl='Senpai\u0027s Kist'; pt='Baú do Senpai'; 'pt-BR'='Baú do Senpai'; ru='Сундук Senpai'; sv='Senpais Kista'; 'zh-CN'='Senpai的宝箱'; 'zh-TW'='Senpai的寶箱'; uk='Скриня Senpai' }
    "azrael.senpai.trigger_scan" = @{ da='Udløs manuel scanning'; de='Manuelles Scannen auslösen'; es='Activar escaneo manual'; fr='Déclencher l\u0027analyse manuelle'; it='Attiva scansione manuale'; ja='手動スキャンを実行'; ko='수동 검색 실행'; nl='Handmatige scan starten'; pt='Acionar varredura manual'; 'pt-BR'='Acionar varredura manual'; ru='Запустить ручное сканирование'; sv='Trigga manuell skanning'; 'zh-CN'='触发手动扫描'; 'zh-TW'='觸發手動掃描'; uk='Запустити ручне сканування' }
    "azrael.smut.title" = @{ da='S.M.U.T. - Museumsbundleinspektør'; de='S.M.U.T. - Museumsbündel-Inspektor'; es='S.M.U.T. - Inspector de lotes del museo'; fr='S.M.U.T. - Inspecteur de lots du musée'; it='S.M.U.T. - Ispettore bundle museo'; ja='S.M.U.T. - 博物館バンドル検査'; ko='S.M.U.T. - 박물관 번들 검사기'; nl='S.M.U.T. - Museumbundelinspecteur'; pt='S.M.U.T. - Inspetor de Pacotes do Museu'; 'pt-BR'='S.M.U.T. - Inspetor de Pacotes do Museu'; ru='S.M.U.T. - Инспектор наборов музея'; sv='S.M.U.T. - Museumbuntinspektör'; 'zh-CN'='S.M.U.T. - 博物馆捆绑包检查器'; 'zh-TW'='S.M.U.T. - 博物館套組檢查器'; uk='S.M.U.T. - Інспектор наборів музею' }
    "azrael.tab.almanac" = @{ da='Almanak'; de='Almanach'; es='Almanaque'; fr='Almanach'; it='Almanacco'; ja='アルマナック'; ko='앨머넥'; nl='Almanak'; pt='Almanaque'; 'pt-BR'='Almanaque'; ru='Альманах'; sv='Almanacka'; 'zh-CN'='年鉴'; 'zh-TW'='年鑑'; uk='Альманах' }
    "azrael.tab.birthday" = @{ da='Fødselsdag'; de='Geburtstag'; es='Cumpleaños'; fr='Anniversaire'; it='Compleanno'; ja='誕生日'; ko='생일'; nl='Verjaardag'; pt='Aniversário'; 'pt-BR'='Aniversário'; ru='День рождения'; sv='Födelsedag'; 'zh-CN'='生日'; 'zh-TW'='生日'; uk='День народження' }
    "azrael.tab.birthright" = @{ da='Birthright'; de='Birthright'; es='Birthright'; fr='Birthright'; it='Birthright'; ja='バースライト'; ko='Birthright'; nl='Birthright'; pt='Birthright'; 'pt-BR'='Birthright'; ru='Birthright'; sv='Birthright'; 'zh-CN'='Birthright'; 'zh-TW'='Birthright'; uk='Birthright' }
    "azrael.tab.senpais_chest" = @{ da='Senpais Kiste'; de='Senpais Truhe'; es='Cofre de Senpai'; fr='Coffre de Senpai'; it='Forziere di Senpai'; ja='Senpaiのチェスト'; ko='Senpai의 상자'; nl='Senpai\u0027s Kist'; pt='Baú do Senpai'; 'pt-BR'='Baú do Senpai'; ru='Сундук Senpai'; sv='Senpais Kista'; 'zh-CN'='Senpai的宝箱'; 'zh-TW'='Senpai的寶箱'; uk='Скриня Senpai' }
    "azrael.tab.smut" = @{ da='S.M.U.T.'; de='S.M.U.T.'; es='S.M.U.T.'; fr='S.M.U.T.'; it='S.M.U.T.'; ja='S.M.U.T.'; ko='S.M.U.T.'; nl='S.M.U.T.'; pt='S.M.U.T.'; 'pt-BR'='S.M.U.T.'; ru='S.M.U.T.'; sv='S.M.U.T.'; 'zh-CN'='S.M.U.T.'; 'zh-TW'='S.M.U.T.'; uk='S.M.U.T.' }
    "azrael.tab.the_vault" = @{ da='The Vault'; de='The Vault'; es='The Vault'; fr='The Vault'; it='The Vault'; ja='The Vault'; ko='The Vault'; nl='The Vault'; pt='The Vault'; 'pt-BR'='The Vault'; ru='The Vault'; sv='The Vault'; 'zh-CN'='The Vault'; 'zh-TW'='The Vault'; uk='The Vault' }
    "azrael.tab.todo" = @{ da='Todo'; de='Todo'; es='Todo'; fr='Todo'; it='Todo'; ja='Todo'; ko='Todo'; nl='Todo'; pt='Todo'; 'pt-BR'='Todo'; ru='Todo'; sv='Todo'; 'zh-CN'='Todo'; 'zh-TW'='Todo'; uk='Todo' }
    "azrael.tab.trinket_fortune" = @{ da='Trinket Fortune'; de='Trinket Fortune'; es='Trinket Fortune'; fr='Trinket Fortune'; it='Trinket Fortune'; ja='Trinket Fortune'; ko='Trinket Fortune'; nl='Trinket Fortune'; pt='Trinket Fortune'; 'pt-BR'='Trinket Fortune'; ru='Trinket Fortune'; sv='Trinket Fortune'; 'zh-CN'='Trinket Fortune'; 'zh-TW'='Trinket Fortune'; uk='Trinket Fortune' }
    "azrael.todo.save" = @{ da='Gem data'; de='Daten speichern'; es='Guardar datos'; fr='Enregistrer les données'; it='Salva dati'; ja='データを保存'; ko='데이터 저장'; nl='Gegevens opslaan'; pt='Guardar dados'; 'pt-BR'='Salvar dados'; ru='Сохранить данные'; sv='Spara data'; 'zh-CN'='保存数据'; 'zh-TW'='儲存資料'; uk='Зберегти дані' }
    "azrael.todo.title" = @{ da='Sunhaven Todo'; de='Sunhaven Todo'; es='Sunhaven Todo'; fr='Sunhaven Todo'; it='Sunhaven Todo'; ja='Sunhaven Todo'; ko='Sunhaven Todo'; nl='Sunhaven Todo'; pt='Sunhaven Todo'; 'pt-BR'='Sunhaven Todo'; ru='Sunhaven Todo'; sv='Sunhaven Todo'; 'zh-CN'='Sunhaven待办'; 'zh-TW'='Sunhaven待辦'; uk='Sunhaven Todo' }
    "azrael.todo.toggle_hud" = @{ da='Skift HUD'; de='HUD umschalten'; es='Alternar HUD'; fr='Basculer l\u0027ATH'; it='Attiva/disattiva HUD'; ja='HUD切り替え'; ko='HUD 전환'; nl='HUD wisselen'; pt='Alternar HUD'; 'pt-BR'='Alternar HUD'; ru='Переключить HUD'; sv='Växla HUD'; 'zh-CN'='切换HUD'; 'zh-TW'='切換HUD'; uk='Перемкнути HUD' }
    "azrael.todo.toggle_ui" = @{ da='Skift UI'; de='UI umschalten'; es='Alternar IU'; fr='Basculer l\u0027IU'; it='Attiva/disattiva UI'; ja='UI切り替え'; ko='UI 전환'; nl='UI wisselen'; pt='Alternar IU'; 'pt-BR'='Alternar UI'; ru='Переключить UI'; sv='Växla UI'; 'zh-CN'='切换UI'; 'zh-TW'='切換UI'; uk='Перемкнути UI' }
    "azrael.trinket.not_loaded" = @{ da='Trinket Fortune ikke indlæst.'; de='Trinket Fortune nicht geladen.'; es='Trinket Fortune no cargado.'; fr='Trinket Fortune non chargé.'; it='Trinket Fortune non caricato.'; ja='Trinket Fortuneが読み込まれていません。'; ko='Trinket Fortune가 로드되지 않았습니다.'; nl='Trinket Fortune niet geladen.'; pt='Trinket Fortune não carregado.'; 'pt-BR'='Trinket Fortune não carregado.'; ru='Trinket Fortune не загружен.'; sv='Trinket Fortune inte laddad.'; 'zh-CN'='Trinket Fortune未加载。'; 'zh-TW'='Trinket Fortune未載入。'; uk='Trinket Fortune не завантажено.' }
    "azrael.vault.currencies" = @{ da='Boks-valutaer:'; de='Tresor-Währungen:'; es='Divisas de la Bóveda:'; fr='Devises du Coffre-fort :'; it='Valute della Cassaforte:'; ja='Vaultの通貨：'; ko='금고 통화:'; nl='Kluisvaluta\u0027s:'; pt='Moedas do Cofre:'; 'pt-BR'='Moedas do Cofre:'; ru='Валюты Хранилища:'; sv='Valvvalutor:'; 'zh-CN'='Vault货币：'; 'zh-TW'='Vault貨幣：'; uk='Валюти Сховища:' }
    "azrael.vault.empty" = @{ da='  (boks tom eller ikke indlæst)'; de='  (Tresor leer oder nicht geladen)'; es='  (bóveda vacía o no cargada)'; fr='  (coffre-fort vide ou non chargé)'; it='  (cassaforte vuota o non caricata)'; ja='  (Vaultが空または未読み込み)'; ko='  (금고가 비어 있거나 로드되지 않음)'; nl='  (kluis leeg of niet geladen)'; pt='  (cofre vazio ou não carregado)'; 'pt-BR'='  (cofre vazio ou não carregado)'; ru='  (хранилище пусто или не загружено)'; sv='  (valvet tomt eller inte laddat)'; 'zh-CN'='  (vault为空或未加载)'; 'zh-TW'='  (vault為空或未載入)'; uk='  (сховище порожнє або не завантажено)' }
    "azrael.vault.inspector_hint" = @{ da='Flyttet fra The Vault-indstillinger; vedvarer i com.azraelgodking.havendevtools.cfg ([The Vault]-sektionen).'; de='Aus den The Vault-Einstellungen verschoben; bleibt in com.azraelgodking.havendevtools.cfg ([The Vault]-Abschnitt) erhalten.'; es='Movido de la configuración de The Vault; persiste en com.azraelgodking.havendevtools.cfg (sección [The Vault]).'; fr='Déplacé des paramètres de The Vault ; persiste dans com.azraelgodking.havendevtools.cfg (section [The Vault]).'; it='Spostato dalle impostazioni di The Vault; persistente in com.azraelgodking.havendevtools.cfg (sezione [The Vault]).'; ja='The Vaultの設定から移動しました。com.azraelgodking.havendevtools.cfg（[The Vault]セクション）に保存されます。'; ko='The Vault 설정에서 이동됨. com.azraelgodking.havendevtools.cfg ([The Vault] 섹션)에 유지됩니다.'; nl='Verplaatst vanuit The Vault-instellingen; blijft bestaan in com.azraelgodking.havendevtools.cfg ([The Vault]-sectie).'; pt='Movido das definições do The Vault; persiste em com.azraelgodking.havendevtools.cfg (secção [The Vault]).'; 'pt-BR'='Movido das configurações do The Vault; persiste em com.azraelgodking.havendevtools.cfg (seção [The Vault]).'; ru='Перемещено из настроек The Vault; сохраняется в com.azraelgodking.havendevtools.cfg (раздел [The Vault]).'; sv='Flyttat från The Vault-inställningar; består i com.azraelgodking.havendevtools.cfg ([The Vault]-sektionen).'; 'zh-CN'='已从The Vault设置中移出；保留在com.azraelgodking.havendevtools.cfg（[The Vault]部分）中。'; 'zh-TW'='已從The Vault設定中移出；保留在com.azraelgodking.havendevtools.cfg（[The Vault]部分）中。'; uk='Переміщено з налаштувань The Vault; зберігається в com.azraelgodking.havendevtools.cfg (розділ [The Vault]).' }
    "azrael.vault.inspector_toggle" = @{ da=' Fuld boks-inspektør (nuller + Debug-fane + fuld HUD)'; de=' Voller Tresor-Inspektor (Nullen + Debug-Tab + volles HUD)'; es=' Inspector de bóveda completo (ceros + pestaña Debug + HUD completo)'; fr=' Inspecteur de coffre-fort complet (zéros + onglet Debug + HUD complet)'; it=' Ispettore cassaforte completo (zeri + scheda Debug + HUD completo)'; ja=' フルVaultインスペクター（ゼロ + デバッグタブ + フルHUD）'; ko=' 전체 금고 검사기 (zeros + Debug 탭 + 전체 HUD)'; nl=' Volledige kluisinspecteur (nullen + Debug-tab + volledige HUD)'; pt=' Inspetor de cofre completo (zeros + separador Debug + HUD completo)'; 'pt-BR'=' Inspetor de cofre completo (zeros + aba Debug + HUD completo)'; ru=' Полный инспектор хранилища (нули + вкладка Debug + полный HUD)'; sv=' Full valvinspektör (nollor + Debug-flik + full HUD)'; 'zh-CN'=' 完整Vault检查器（zeros + Debug标签 + 完整HUD）'; 'zh-TW'=' 完整Vault檢查器（zeros + Debug標籤 + 完整HUD）'; uk=' Повний інспектор сховища (нулі + вкладка Debug + повний HUD)' }
    "azrael.vault.title" = @{ da='The Vault'; de='The Vault'; es='The Vault'; fr='The Vault'; it='The Vault'; ja='The Vault'; ko='The Vault'; nl='The Vault'; pt='The Vault'; 'pt-BR'='The Vault'; ru='The Vault'; sv='The Vault'; 'zh-CN'='The Vault'; 'zh-TW'='The Vault'; uk='The Vault' }
    "devtools.auth.hint" = @{ da='Brug dette til at generere hashes for nye autoriserede Steam-ID\u0027er'; de='Verwenden Sie dies, um Hashes für neue autorisierte Steam-IDs zu generieren'; es='Úsalo para generar hashes para nuevos Steam IDs autorizados'; fr='Utilisez ceci pour générer des hachages pour de nouveaux Steam IDs autorisés'; it='Usalo per generare hash per nuovi Steam ID autorizzati'; ja='新しい認定Steam IDのハッシュを生成するために使用します'; ko='새로운 인증된 Steam ID의 해시를 생성하는 데 사용합니다'; nl='Gebruik dit om hashes te genereren voor nieuwe geautoriseerde Steam-ID\u0027s'; pt='Usa isto para gerar hashes para novos Steam IDs autorizados'; 'pt-BR'='Use isto para gerar hashes para novos Steam IDs autorizados'; ru='Используйте это для генерации хэшей для новых авторизованных Steam ID'; sv='Använd detta för att generera hashar för nya auktoriserade Steam-ID:n'; 'zh-CN'='使用此功能为新的授权Steam ID生成哈希值'; 'zh-TW'='使用此功能為新的授權Steam ID產生雜湊值'; uk='Використовуйте це для генерації хешів для нових авторизованих Steam ID' }
    "devtools.auth.logHash" = @{ da='Log aktuelt Steam ID-hash'; de='Aktuellen Steam-ID-Hash protokollieren'; es='Registrar hash de Steam ID actual'; fr='Enregistrer le hash du Steam ID actuel'; it='Registra hash Steam ID attuale'; ja='現在のSteam IDハッシュをログ出力'; ko='현재 Steam ID 해시 기록'; nl='Log huidige Steam ID-hash'; pt='Registar hash do Steam ID atual'; 'pt-BR'='Registrar hash do Steam ID atual'; ru='Записать хеш текущего Steam ID'; sv='Logga aktuellt Steam ID-hash'; 'zh-CN'='记录当前Steam ID哈希值'; 'zh-TW'='記錄目前Steam ID雜湊值'; uk='Записати хеш поточного Steam ID' }
    "devtools.auth.title" = @{ da='Autoriseringshash-generator:'; de='Autorisierungs-Hash-Generator:'; es='Generador de hashes de autorización:'; fr='Générateur de hachage d\u0027autorisation :'; it='Generatore di hash di autorizzazione:'; ja='認証ハッシュ生成ツール：'; ko='인증 해시 생성기:'; nl='Autorisatiehash-generator:'; pt='Gerador de Hash de Autorização:'; 'pt-BR'='Gerador de Hash de Autorização:'; ru='Генератор хэша авторизации:'; sv='Auktoriseringshashgenerator:'; 'zh-CN'='授权哈希生成器：'; 'zh-TW'='授權雜湊產生器：'; uk='Генератор хешу авторизації:' }
    "devtools.config" = @{ da='Config:'; de='Config:'; es='Config:'; fr='Config :'; it='Config:'; ja='Config:'; ko='Config:'; nl='Config:'; pt='Config:'; 'pt-BR'='Config:'; ru='Config:'; sv='Config:'; 'zh-CN'='Config:'; 'zh-TW'='Config:'; uk='Config:' }
    "devtools.config.reload" = @{ da='Genindlæs HavenDevTools-config'; de='HavenDevTools-Konfiguration neu laden'; es='Recargar configuración de HavenDevTools'; fr='Recharger la configuration de HavenDevTools'; it='Ricarica configurazione HavenDevTools'; ja='HavenDevTools設定を再読み込み'; ko='HavenDevTools 설정 다시 불러오기'; nl='HavenDevTools-config herladen'; pt='Recarregar configuração do HavenDevTools'; 'pt-BR'='Recarregar configuração do HavenDevTools'; ru='Перезагрузить конфигурацию HavenDevTools'; sv='Ladda om HavenDevTools-konfiguration'; 'zh-CN'='重新加载HavenDevTools配置'; 'zh-TW'='重新載入HavenDevTools設定'; uk='Перезавантажити конфігурацію HavenDevTools' }
    "devtools.console.commands" = @{ da='Kommandoer: spawn <id> [antal] | tp <scene> | time.set <time> | reload.config'; de='Befehle: spawn <id> [Menge] | tp <Szene> | time.set <Stunde> | reload.config'; es='Comandos: spawn <id> [cant] | tp <escena> | time.set <hora> | reload.config'; fr='Commandes : spawn <id> [qty] | tp <scène> | time.set <heure> | reload.config'; it='Comandi: spawn <id> [qty] | tp <scena> | time.set <ora> | reload.config'; ja='コマンド：spawn <id> [数量] | tp <シーン> | time.set <時> | reload.config'; ko='명령어: spawn <id> [수량] | tp <장면> | time.set <시간> | reload.config'; nl='Commando\u0027s: spawn <id> [aantal] | tp <scene> | time.set <uur> | reload.config'; pt='Comandos: spawn <id> [qtd] | tp <cenário> | time.set <hora> | reload.config'; 'pt-BR'='Comandos: spawn <id> [qtd] | tp <cena> | time.set <hora> | reload.config'; ru='Команды: spawn <id> [кол-во] | tp <сцена> | time.set <час> | reload.config'; sv='Kommandon: spawn <id> [antal] | tp <scen> | time.set <timme> | reload.config'; 'zh-CN'='命令：spawn <id> [数量] | tp <场景> | time.set <小时> | reload.config'; 'zh-TW'='指令：spawn <id> [數量] | tp <場景> | time.set <小時> | reload.config'; uk='Команди: spawn <id> [кількість] | tp <сцена> | time.set <година> | reload.config' }
    "devtools.console.execute" = @{ da='Udfør'; de='Ausführen'; es='Ejecutar'; fr='Exécuter'; it='Esegui'; ja='実行'; ko='실행'; nl='Uitvoeren'; pt='Executar'; 'pt-BR'='Executar'; ru='Выполнить'; sv='Kör'; 'zh-CN'='执行'; 'zh-TW'='執行'; uk='Виконати' }
    "devtools.console.hint" = @{ da='Skriv kommandoer og tryk Enter. Understøttet: spawn, tp, time.set, reload.config'; de='Befehle eingeben und Enter drücken. Unterstützt: spawn, tp, time.set, reload.config'; es='Escribe comandos y presiona Intro. Soportado: spawn, tp, time.set, reload.config'; fr='Tapez des commandes et appuyez sur Entrée. Pris en charge : spawn, tp, time.set, reload.config'; it='Digita comandi e premi Invio. Supportati: spawn, tp, time.set, reload.config'; ja='コマンドを入力してEnterを押してください。サポート：spawn、tp、time.set、reload.config'; ko='명령어를 입력하고 Enter를 누르세요. 지원: spawn, tp, time.set, reload.config'; nl='Typ commando\u0027s en druk op Enter. Ondersteund: spawn, tp, time.set, reload.config'; pt='Escreve comandos e prime Enter. Suportado: spawn, tp, time.set, reload.config'; 'pt-BR'='Digite comandos e pressione Enter. Suportado: spawn, tp, time.set, reload.config'; ru='Введите команды и нажмите Enter. Поддерживается: spawn, tp, time.set, reload.config'; sv='Skriv kommandon och tryck Enter. Stöds: spawn, tp, time.set, reload.config'; 'zh-CN'='输入命令并按回车。支持：spawn、tp、time.set、reload.config'; 'zh-TW'='輸入指令並按Enter。支援：spawn、tp、time.set、reload.config'; uk='Введіть команди та натисніть Enter. Підтримується: spawn, tp, time.set, reload.config' }
    "devtools.console.init" = @{ da='(Konsoltjeneste initialiserer...)'; de='(Konsolendienst wird initialisiert...)'; es='(Servicio de consola inicializando...)'; fr='(Service console en cours d\u0027initialisation...)'; it='(Servizio console in inizializzazione...)'; ja='（コンソールサービスを初期化中...）'; ko='(콘솔 서비스 초기화 중...)'; nl='(Console-service wordt geïnitialiseerd...)'; pt='(Serviço da consola a inicializar...)'; 'pt-BR'='(Serviço do console inicializando...)'; ru='(Инициализация консольного сервиса...)'; sv='(Konsoltjänst initierar...)'; 'zh-CN'='（控制台服务初始化中...）'; 'zh-TW'='（控制台服務初始化中...）'; uk='(Ініціалізація консольного сервісу...)' }
    "devtools.console.output" = @{ da='Output:'; de='Output:'; es='Salida:'; fr='Sortie :'; it='Output:'; ja='出力：'; ko='출력:'; nl='Output:'; pt='Saída:'; 'pt-BR'='Saída:'; ru='Вывод:'; sv='Utdata:'; 'zh-CN'='输出：'; 'zh-TW'='輸出：'; uk='Вивід:' }
    "devtools.console.title" = @{ da='Kommandokonsol'; de='Befehlskonsole'; es='Consola de comandos'; fr='Console de commandes'; it='Console comandi'; ja='コマンドコンソール'; ko='명령 콘솔'; nl='Opdrachtconsole'; pt='Consola de Comandos'; 'pt-BR'='Console de Comandos'; ru='Командная консоль'; sv='Kommandokonsol'; 'zh-CN'='命令控制台'; 'zh-TW'='命令控制台'; uk='Командна консоль' }
    "devtools.currency.gold" = @{ da='Guld: {0:N0}'; de='Gold: {0:N0}'; es='Oro: {0:N0}'; fr='Or : {0:N0}'; it='Oro: {0:N0}'; ja='ゴールド：{0:N0}'; ko='골드: {0:N0}'; nl='Goud: {0:N0}'; pt='Ouro: {0:N0}'; 'pt-BR'='Ouro: {0:N0}'; ru='Золото: {0:N0}'; sv='Guld: {0:N0}'; 'zh-CN'='金币：{0:N0}'; 'zh-TW'='金幣：{0:N0}'; uk='Золото: {0:N0}' }
    "devtools.currency.inventory" = @{ da='Inventar-valutaer:'; de='Inventar-Währungen:'; es='Divisas del inventario:'; fr='Devises de l\u0027inventaire :'; it='Valute inventario:'; ja='インベントリ通貨：'; ko='인벤토리 통화:'; nl='Inventarisvaluta\u0027s:'; pt='Moedas do inventário:'; 'pt-BR'='Moedas do inventário:'; ru='Валюты инвентаря:'; sv='Inventarievalutor:'; 'zh-CN'='库存货币：'; 'zh-TW'='庫存貨幣：'; uk='Валюти інвентарю:' }
    "devtools.currency.none" = @{ da='  (ingen)'; de='  (keine)'; es='  (ninguna)'; fr='  (aucune)'; it='  (nessuno)'; ja='  (なし)'; ko='  (없음)'; nl='  (geen)'; pt='  (nenhuma)'; 'pt-BR'='  (nenhuma)'; ru='  (нет)'; sv='  (ingen)'; 'zh-CN'='  (无)'; 'zh-TW'='  (無)'; uk='  (немає)' }
    "devtools.currency.orbs" = @{ da='Orber: {0:N0}'; de='Orbs: {0:N0}'; es='Orbes: {0:N0}'; fr='Orbes : {0:N0}'; it='Sfere: {0:N0}'; ja='オーブ：{0:N0}'; ko='오브: {0:N0}'; nl='Orbs: {0:N0}'; pt='Orbes: {0:N0}'; 'pt-BR'='Orbes: {0:N0}'; ru='Сферы: {0:N0}'; sv='Orbs: {0:N0}'; 'zh-CN'='宝珠：{0:N0}'; 'zh-TW'='寶珠：{0:N0}'; uk='Сфери: {0:N0}' }
    "devtools.currency.tickets" = @{ da='Billetter: {0:N0}'; de='Tickets: {0:N0}'; es='Tickets: {0:N0}'; fr='Tickets : {0:N0}'; it='Biglietti: {0:N0}'; ja='チケット：{0:N0}'; ko='티켓: {0:N0}'; nl='Tickets: {0:N0}'; pt='Bilhetes: {0:N0}'; 'pt-BR'='Ingressos: {0:N0}'; ru='Билеты: {0:N0}'; sv='Biljetter: {0:N0}'; 'zh-CN'='票券：{0:N0}'; 'zh-TW'='票券：{0:N0}'; uk='Квитки: {0:N0}' }
    "devtools.currency.title" = @{ da='Valutaspore'; de='Währungs-Tracker'; es='Rastreador de divisas'; fr='Suivi des devises'; it='Tracciatore valute'; ja='通貨トラッカー'; ko='통화 추적기'; nl='Valuta-tracker'; pt='Rastreador de moedas'; 'pt-BR'='Rastreador de moedas'; ru='Трекер валют'; sv='Valutaspårare'; 'zh-CN'='货币追踪器'; 'zh-TW'='貨幣追蹤器'; uk='Трекер валют' }
    "devtools.currency.unavailable" = @{ da='Valutaspore ikke tilgængelig'; de='Währungs-Tracker nicht verfügbar'; es='Rastreador de divisas no disponible'; fr='Suivi des devises non disponible'; it='Tracciatore valute non disponibile'; ja='通貨トラッカーは利用できません'; ko='통화 추적기를 사용할 수 없습니다'; nl='Valuta-tracker niet beschikbaar'; pt='Rastreador de moedas indisponível'; 'pt-BR'='Rastreador de moedas indisponível'; ru='Трекер валют недоступен'; sv='Valutaspårare ej tillgänglig'; 'zh-CN'='货币追踪器不可用'; 'zh-TW'='貨幣追蹤器不可用'; uk='Трекер валют недоступний' }
    "devtools.currency.vault" = @{ da='Boks-valutaer:'; de='Tresor-Währungen:'; es='Divisas de la Bóveda:'; fr='Devises du Coffre-fort :'; it='Valute della Cassaforte:'; ja='Vaultの通貨：'; ko='금고 통화:'; nl='Kluisvaluta\u0027s:'; pt='Moedas do Cofre:'; 'pt-BR'='Moedas do Cofre:'; ru='Валюты Хранилища:'; sv='Valvvalutor:'; 'zh-CN'='Vault货币：'; 'zh-TW'='Vault貨幣：'; uk='Валюти Сховища:' }
    "devtools.currency.vaultEmpty" = @{ da='  (boks tom)'; de='  (Tresor leer)'; es='  (bóveda vacía)'; fr='  (coffre-fort vide)'; it='  (cassaforte vuota)'; ja='  (Vaultが空)'; ko='  (금고가 비어 있음)'; nl='  (kluis leeg)'; pt='  (cofre vazio)'; 'pt-BR'='  (cofre vazio)'; ru='  (хранилище пусто)'; sv='  (valvet tomt)'; 'zh-CN'='  (vault为空)'; 'zh-TW'='  (vault為空)'; uk='  (сховище порожнє)' }
    "devtools.currency.vaultMissing" = @{ da='(The Vault ikke installeret)'; de='(The Vault nicht installiert)'; es='(The Vault no instalado)'; fr='(The Vault non installé)'; it='(The Vault non installato)'; ja='(The Vaultがインストールされていません)'; ko='(The Vault가 설치되지 않음)'; nl='(The Vault niet geïnstalleerd)'; pt='(The Vault não instalado)'; 'pt-BR'='(The Vault não instalado)'; ru='(The Vault не установлен)'; sv='(The Vault inte installerat)'; 'zh-CN'='(The Vault未安装)'; 'zh-TW'='(The Vault未安裝)'; uk='(The Vault не встановлено)' }
    "devtools.extensions" = @{ da='Udvidelser'; de='Erweiterungen'; es='Extensiones'; fr='Extensions'; it='Estensioni'; ja='拡張機能'; ko='확장'; nl='Extensies'; pt='Extensões'; 'pt-BR'='Extensões'; ru='Расширения'; sv='Tillägg'; 'zh-CN'='扩展'; 'zh-TW'='擴充功能'; uk='Розширення' }
    "devtools.extensions.none" = @{ da='Ingen udvidelsespaneler registreret. Mods kan implementere IDevToolsPanel og kalde DevToolsRegistry.Register() for at tilføje paneler her.'; de='Keine Erweiterungspanels registriert. Mods können IDevToolsPanel implementieren und DevToolsRegistry.Register() aufrufen, um hier Panels hinzuzufügen.'; es='No hay paneles de extensión registrados. Los mods pueden implementar IDevToolsPanel y llamar a DevToolsRegistry.Register() para añadir paneles aquí.'; fr='Aucun panneau d\u0027extension enregistré. Les mods peuvent implémenter IDevToolsPanel et appeler DevToolsRegistry.Register() pour ajouter des panneaux ici.'; it='Nessun pannello di estensione registrato. Le mod possono implementare IDevToolsPanel e chiamare DevToolsRegistry.Register() per aggiungere pannelli qui.'; ja='拡張パネルが登録されていません。ModはIDevToolsPanelを実装し、DevToolsRegistry.Register()を呼び出してここにパネルを追加できます。'; ko='등록된 확장 패널이 없습니다. 모드는 IDevToolsPanel을 구현하고 DevToolsRegistry.Register()를 호출하여 여기에 패널을 추가할 수 있습니다.'; nl='Geen extensiepanelen geregistreerd. Mods kunnen IDevToolsPanel implementeren en DevToolsRegistry.Register() aanroepen om hier panelen toe te voegen.'; pt='Nenhum painel de extensão registado. Os mods podem implementar IDevToolsPanel e chamar DevToolsRegistry.Register() para adicionar painéis aqui.'; 'pt-BR'='Nenhum painel de extensão registrado. Mods podem implementar IDevToolsPanel e chamar DevToolsRegistry.Register() para adicionar painéis aqui.'; ru='Панели расширений не зарегистрированы. Моды могут реализовать IDevToolsPanel и вызвать DevToolsRegistry.Register(), чтобы добавить панели здесь.'; sv='Inga tilläggspaneler registrerade. Moddar kan implementera IDevToolsPanel och anropa DevToolsRegistry.Register() för att lägga till paneler här.'; 'zh-CN'='未注册扩展面板。模组可以实现IDevToolsPanel并调用DevToolsRegistry.Register()来在此处添加面板。'; 'zh-TW'='未註冊擴充面板。模組可以實作IDevToolsPanel並呼叫DevToolsRegistry.Register()來在此處新增面板。'; uk='Панелі розширень не зареєстровано. Моди можуть реалізувати IDevToolsPanel та викликати DevToolsRegistry.Register(), щоб додати панелі тут.' }
    "devtools.items.held" = @{ da='Holdt: {0} ({1})'; de='Gehalten: {0} ({1})'; es='Sostenido: {0} ({1})'; fr='Tenu : {0} ({1})'; it='Tenuto: {0} ({1})'; ja='所持：{0}（{1}）'; ko='소지: {0} ({1})'; nl='Vastgehouden: {0} ({1})'; pt='Segurado: {0} ({1})'; 'pt-BR'='Segurado: {0} ({1})'; ru='В руках: {0} ({1})'; sv='Hållen: {0} ({1})'; 'zh-CN'='手持：{0}（{1}）'; 'zh-TW'='手持：{0}（{1}）'; uk='У руках: {0} ({1})' }
    "devtools.items.heldNone" = @{ da='Holdt: Ingen'; de='Gehalten: Keiner'; es='Sostenido: Ninguno'; fr='Tenu : Aucun'; it='Tenuto: Nessuno'; ja='所持：なし'; ko='소지: 없음'; nl='Vastgehouden: Geen'; pt='Segurado: Nenhum'; 'pt-BR'='Segurado: Nenhum'; ru='В руках: Нет'; sv='Hållen: Ingen'; 'zh-CN'='手持：无'; 'zh-TW'='手持：無'; uk='У руках: Немає' }
    "devtools.items.notFound" = @{ da='Ingen genstande fundet.'; de='Keine Gegenstände gefunden.'; es='No se encontraron artículos.'; fr='Aucun article trouvé.'; it='Nessun oggetto trovato.'; ja='アイテムが見つかりませんでした。'; ko='아이템을 찾을 수 없습니다.'; nl='Geen items gevonden.'; pt='Nenhum item encontrado.'; 'pt-BR'='Nenhum item encontrado.'; ru='Предметы не найдены.'; sv='Inga föremål hittades.'; 'zh-CN'='未找到物品。'; 'zh-TW'='未找到物品。'; uk='Предметів не знайдено.' }
    "devtools.items.title" = @{ da='Genstandsinpektør'; de='Gegenstandsinspektor'; es='Inspector de artículos'; fr='Inspecteur d\u0027articles'; it='Ispettore oggetti'; ja='アイテム検査'; ko='아이템 검사기'; nl='Iteminspecteur'; pt='Inspetor de itens'; 'pt-BR'='Inspetor de itens'; ru='Инспектор предметов'; sv='Föremålsinspektör'; 'zh-CN'='物品检查器'; 'zh-TW'='物品檢查器'; uk='Інспектор предметів' }
    "devtools.log.export" = @{ da='Eksportér'; de='Exportieren'; es='Exportar'; fr='Exporter'; it='Esporta'; ja='エクスポート'; ko='내보내기'; nl='Exporteren'; pt='Exportar'; 'pt-BR'='Exportar'; ru='Экспорт'; sv='Exportera'; 'zh-CN'='导出'; 'zh-TW'='匯出'; uk='Експорт' }
    "devtools.log.init" = @{ da='(Logfremviser initialiserer...)'; de='(Log-Viewer wird initialisiert...)'; es='(Visor de registros inicializando...)'; fr='(Visionneuse de journal en cours d\u0027initialisation...)'; it='(Visualizzatore log in inizializzazione...)'; ja='（ログビューアを初期化中...）'; ko='(로그 뷰어 초기화 중...)'; nl='(Logviewer wordt geïnitialiseerd...)'; pt='(Visualizador de registo a inicializar...)'; 'pt-BR'='(Visualizador de registro inicializando...)'; ru='(Инициализация просмотрщика журнала...)'; sv='(Loggvisare initierar...)'; 'zh-CN'='（日志查看器初始化中...）'; 'zh-TW'='（日誌檢視器初始化中...）'; uk='(Ініціалізація переглядача журналу...)' }
    "devtools.log.level" = @{ da='Niveau:'; de='Stufe:'; es='Nivel:'; fr='Niveau :'; it='Livello:'; ja='レベル：'; ko='레벨:'; nl='Niveau:'; pt='Nível:'; 'pt-BR'='Nível:'; ru='Уровень:'; sv='Nivå:'; 'zh-CN'='级别：'; 'zh-TW'='等級：'; uk='Рівень:' }
    "devtools.log.title" = @{ da='Logfremviser'; de='Log-Viewer'; es='Visor de registros'; fr='Visionneuse de journal'; it='Visualizzatore log'; ja='ログビューア'; ko='로그 뷰어'; nl='Logviewer'; pt='Visualizador de Registo'; 'pt-BR'='Visualizador de Registro'; ru='Просмотрщик журнала'; sv='Loggvisare'; 'zh-CN'='日志查看器'; 'zh-TW'='日誌檢視器'; uk='Переглядач журналу' }
    "devtools.logCurrencyIds" = @{ da='Log alle valuta-ID\u0027er'; de='Alle Währungs-IDs protokollieren'; es='Registrar todos los ID de divisas'; fr='Enregistrer tous les IDs de devises'; it='Registra tutti gli ID valuta'; ja='すべての通貨IDをログ出力'; ko='모든 통화 ID 기록'; nl='Log alle valuta-ID\u0027s'; pt='Registar todos os IDs de moedas'; 'pt-BR'='Registrar todos os IDs de moedas'; ru='Записать все ID валют'; sv='Logga alla valuta-ID:n'; 'zh-CN'='记录所有货币ID'; 'zh-TW'='記錄所有貨幣ID'; uk='Записати всі ID валют' }
    "devtools.logging" = @{ da='Logning:'; de='Protokollierung:'; es='Registro:'; fr='Journalisation :'; it='Logging:'; ja='ロギング：'; ko='로깅:'; nl='Logboekregistratie:'; pt='Registo:'; 'pt-BR'='Registro:'; ru='Ведение журнала:'; sv='Loggning:'; 'zh-CN'='日志记录：'; 'zh-TW'='日誌記錄：'; uk='Журналювання:' }
}

$languages = @('da','de','es','fr','it','ja','ko','nl','pt','pt-BR','ru','sv','zh-CN','zh-TW','uk')

foreach ($key in $keys.Keys) {
    $keyPattern = '"' + [regex]::Escape($key) + '":\s*\{'
    $keyMatch = [regex]::Match($content, $keyPattern)
    if (-not $keyMatch.Success) { Write-Warning "Key not found: $key"; continue }
    
    $startIndex = $keyMatch.Index
    $braceIndex = $content.IndexOf('{', $startIndex + $keyMatch.Length - 1)
    
    $depth = 1
    $pos = $braceIndex + 1
    while ($depth -gt 0 -and $pos -lt $content.Length) {
        $char = $content[$pos]
        if ($char -eq '{') { $depth++ }
        elseif ($char -eq '}') { $depth-- }
        $pos++
    }
    
    $block = $content.Substring($startIndex, $pos - $startIndex)
    $originalBlock = $block
    
    $enMatch = [regex]::Match($block, '"en":\s*"([^"]*)"')
    if (-not $enMatch.Success) { continue }
    $enValue = $enMatch.Groups[1].Value
    
    foreach ($lang in $languages) {
        $trans = $keys[$key][$lang]
        if (-not $trans) { continue }
        
        $linePattern = '"' + [regex]::Escape($lang) + '":\s*"' + [regex]::Escape($enValue) + '"'
        $lineReplacement = '"' + $lang + '":  "' + $trans + '"'
        
        $block = [regex]::Replace($block, $linePattern, $lineReplacement)
    }
    
    if ($block -ne $originalBlock) {
        $content = $content.Remove($startIndex, $pos - $startIndex).Insert($startIndex, $block)
    }
}

$content | Set-Content -Path "HavenDevTools/Localization/strings.json" -Encoding UTF8
Write-Host "Done"
