using System;
using System.Collections.Generic;
using System.Reflection;
using BepInEx.Bootstrap;
using GiftingAssistant.Data;
using GiftingAssistant.Game;
using HarmonyLib;

namespace GiftingAssistant.Integration
{
    /// <summary>
    /// A request to publish (or refresh) a single "gift X today" task in Sun Haven Todo.
    /// The caller resolves the icon/gift names so this bridge stays UI-agnostic.
    /// </summary>
    public sealed class GiftTodoRequest
    {
        public string NpcName { get; }
        public int IconItemId { get; }
        public string GiftNames { get; }

        public GiftTodoRequest(string npcName, int iconItemId, string giftNames)
        {
            NpcName = npcName;
            IconItemId = iconItemId;
            GiftNames = giftNames ?? "";
        }
    }

    /// <summary>
    /// Chainloader-gated, reflection-only bridge to Sun Haven Todo.
    /// Click handlers queue work here; <see cref="ProcessPending"/> flushes once per frame
    /// (batched save, no full-roster scan on every button press).
    /// </summary>
    public sealed class TodoIntegration
    {
        private const string PluginGuid = "com.azraelgodking.sunhaventodo";

        /// <summary>Stable marker placed in every task description so we only touch our own todos.</summary>
        private const string AutoMarker = "Auto-generated by Gifting Assistant";
        private const string TitlePrefix = "Gift ";
        private const string TitleSuffix = " today";

        private bool _availableCached;

        /// <summary>True when Sun Haven Todo is loaded via Chainloader.</summary>
        public bool IsAvailable
        {
            get
            {
                if (_availableCached)
                    return true;
                _availableCached = Chainloader.PluginInfos != null &&
                                   Chainloader.PluginInfos.ContainsKey(PluginGuid);
                return _availableCached;
            }
        }

        /// <summary>When false, the gifting window uses its own roster only (no +Todo button).</summary>
        public bool IsEnabled { get; set; }

        /// <summary>True when ReminderMode is PushToTodo and Sun Haven Todo is loaded.</summary>
        public bool CanPushTodos => IsAvailable && IsEnabled;

        // Cached todo ids (normalized NPC name -> todo id) for O(1) complete/remove.
        private readonly Dictionary<string, string> _todoIdsByNpc =
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        private readonly HashSet<string> _pendingPublish = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        private readonly Dictionary<string, bool> _pendingComplete = new Dictionary<string, bool>(StringComparer.OrdinalIgnoreCase);
        private readonly HashSet<string> _pendingRemove = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        private bool _pendingEnsureAll;
        private bool _pendingRefreshDaily;
        private bool _flushScheduled;

        private TodoContext _cachedContext;
        private bool _contextValid;

        /// <summary>Queue a single NPC gift task ( +Todo button ). Resolves gifts on flush.</summary>
        public void QueuePublish(GiftRosterEntry entry)
        {
            if (!CanPushTodos || entry == null || string.IsNullOrEmpty(entry.NpcName))
                return;
            _pendingPublish.Add(entry.NpcName);
            _pendingRemove.Remove(entry.NpcName);
            ScheduleFlush();
        }

        /// <summary>Queue completion sync for one NPC (gifted toggle / in-game gift).</summary>
        public void QueueComplete(string npcName, bool completed)
        {
            if (!CanPushTodos || string.IsNullOrEmpty(npcName))
                return;
            _pendingComplete[npcName] = completed;
            ScheduleFlush();
        }

        /// <summary>Queue removal of one NPC's gift task (roster remove).</summary>
        public void QueueRemove(string npcName)
        {
            if (!CanPushTodos || string.IsNullOrEmpty(npcName))
                return;
            _pendingRemove.Add(npcName);
            _pendingPublish.Remove(npcName);
            _pendingComplete.Remove(npcName);
            ScheduleFlush();
        }

        /// <summary>Queue ensure-all (character load). Not called from click handlers.</summary>
        public void QueueEnsureAll()
        {
            if (!CanPushTodos)
                return;
            _pendingEnsureAll = true;
            ScheduleFlush();
        }

        /// <summary>Queue daily refresh (new day). Not called from click handlers.</summary>
        public void QueueRefreshDaily()
        {
            if (!CanPushTodos)
                return;
            _pendingRefreshDaily = true;
            ScheduleFlush();
        }

        /// <summary>Legacy immediate API — forwards to queue.</summary>
        public void PublishGiftTodo(GiftTodoRequest request)
        {
            if (request == null || string.IsNullOrEmpty(request.NpcName))
                return;
            _pendingPublish.Add(request.NpcName);
            ScheduleFlush();
        }

        /// <summary>Legacy immediate API — forwards to queue.</summary>
        public void EnsureGiftTodos(IList<GiftTodoRequest> requests)
        {
            QueueEnsureAll();
        }

        /// <summary>Legacy immediate API — forwards to queue.</summary>
        public void RefreshDailyGiftTodos(IList<GiftTodoRequest> requests)
        {
            QueueRefreshDaily();
        }

        /// <summary>Legacy immediate API — forwards to queue.</summary>
        public void CompleteGiftTodo(string npcName, bool completed)
        {
            QueueComplete(npcName, completed);
        }

        /// <summary>Drop tracked ids (character change / daily refresh).</summary>
        public void ResetTracking()
        {
            _todoIdsByNpc.Clear();
            _pendingPublish.Clear();
            _pendingComplete.Clear();
            _pendingRemove.Clear();
            _pendingEnsureAll = false;
            _pendingRefreshDaily = false;
            _flushScheduled = false;
            InvalidateContext();
        }

        /// <summary>Process queued todo work. Call once per frame from PersistentRunner.</summary>
        public void ProcessPending()
        {
            if (!_flushScheduled || !CanPushTodos)
                return;

            _flushScheduled = false;

            if (_pendingRemove.Count == 0 && _pendingPublish.Count == 0 && _pendingComplete.Count == 0 &&
                !_pendingEnsureAll && !_pendingRefreshDaily)
                return;

            try
            {
                var ctx = TryGetContext();
                if (ctx == null)
                {
                    ScheduleFlush();
                    return;
                }

                bool changed = false;

                if (_pendingRefreshDaily)
                {
                    _pendingRefreshDaily = false;
                    changed |= RemoveAllGiftTodos(ctx);
                    _todoIdsByNpc.Clear();
                    changed |= EnsureAllFromRoster(ctx);
                }
                else
                {
                    if (_pendingEnsureAll)
                    {
                        _pendingEnsureAll = false;
                        changed |= EnsureAllFromRoster(ctx);
                    }

                    foreach (string npc in _pendingRemove)
                        changed |= RemoveGiftTodoForNpc(ctx, npc);
                    _pendingRemove.Clear();

                    foreach (string npc in _pendingPublish)
                    {
                        changed |= RemoveGiftTodoForNpc(ctx, npc);
                        changed |= PublishForNpc(ctx, npc, skipIfExists: false);
                    }
                    _pendingPublish.Clear();

                    foreach (var kvp in _pendingComplete)
                        changed |= CompleteForNpc(ctx, kvp.Key, kvp.Value);
                    _pendingComplete.Clear();
                }

                if (changed)
                    TrySaveTodoData(ctx.PluginType);
            }
            catch (Exception ex)
            {
                Plugin.Log?.LogWarning($"[GiftingAssistant] Todo flush failed: {ex.Message}");
                ScheduleFlush();
            }
        }

        private void ScheduleFlush()
        {
            _flushScheduled = true;
        }

        private void InvalidateContext()
        {
            _contextValid = false;
            _cachedContext = null;
        }

        private bool EnsureAllFromRoster(TodoContext ctx)
        {
            bool changed = false;
            var manager = Plugin.GetManager();
            if (manager == null)
                return false;

            foreach (var entry in manager.GetEntries())
            {
                if (entry == null || string.IsNullOrEmpty(entry.NpcName))
                    continue;
                changed |= PublishForNpc(ctx, entry.NpcName, skipIfExists: true);
            }

            return changed;
        }

        private bool PublishForNpc(TodoContext ctx, string npcName, bool skipIfExists = true)
        {
            var entry = Plugin.GetManager()?.GetEntry(npcName);
            if (entry == null)
                return false;

            GiftSuggestionResolver.RefreshPrimaryIconForNpc(npcName);
            int iconId = GiftSuggestionResolver.ResolvePrimaryIconId(entry, forceRefresh: true);
            string names = GiftSuggestionResolver.ResolveGiftNames(entry, 3);
            return AddGiftTodo(ctx, new GiftTodoRequest(entry.NpcName, iconId, names), skipIfExists);
        }

        private bool CompleteForNpc(TodoContext ctx, string npcName, bool completed)
        {
            string normalized = GiftGameData.NormalizeNpcName(npcName);
            if (string.IsNullOrEmpty(normalized))
                return false;

            string todoId = FindTodoIdForNpc(ctx, normalized, npcName);
            if (string.IsNullOrEmpty(todoId))
                return false;

            var getById = ctx.GetTodoByIdMethod;
            object todo = getById?.Invoke(ctx.Manager, new object[] { todoId });
            if (todo == null)
            {
                _todoIdsByNpc.Remove(normalized);
                return false;
            }

            bool isCompleted = GetTodoCompleted(todo);
            if (isCompleted == completed)
                return false;

            ctx.ToggleCompleteMethod?.Invoke(ctx.Manager, new object[] { todoId });
            return true;
        }

        private bool RemoveGiftTodoForNpc(TodoContext ctx, string npcName)
        {
            string normalized = GiftGameData.NormalizeNpcName(npcName);
            string todoId = FindTodoIdForNpc(ctx, normalized, npcName);
            if (string.IsNullOrEmpty(todoId))
                return false;

            ctx.RemoveTodoMethod?.Invoke(ctx.Manager, new object[] { todoId });
            _todoIdsByNpc.Remove(normalized);
            return true;
        }

        private string FindTodoIdForNpc(TodoContext ctx, string normalized, string displayName)
        {
            if (_todoIdsByNpc.TryGetValue(normalized, out string cached) && !string.IsNullOrEmpty(cached))
            {
                var getById = ctx.GetTodoByIdMethod;
                object todo = getById?.Invoke(ctx.Manager, new object[] { cached });
                if (todo != null && IsOurGiftTodoForNpc(todo, displayName))
                    return cached;

                _todoIdsByNpc.Remove(normalized);
            }

            string title = BuildTitle(displayName);
            string id = FindOurGiftTodoIdByTitle(ctx, title);
            if (!string.IsNullOrEmpty(id))
                _todoIdsByNpc[normalized] = id;
            return id;
        }

        private string FindOurGiftTodoIdByTitle(TodoContext ctx, string title)
        {
            try
            {
                foreach (var todo in EnumerateAllTodos(ctx))
                {
                    if (todo == null || !IsOurTodo(todo))
                        continue;
                    if (string.Equals(GetTodoTitle(todo), title, StringComparison.OrdinalIgnoreCase))
                        return GetTodoId(todo);
                }
            }
            catch (Exception ex)
            {
                Plugin.Log?.LogDebug($"[GiftingAssistant] FindOurGiftTodoIdByTitle: {ex.Message}");
            }

            return null;
        }

        private static string FindActiveTodoIdByTitle(TodoContext ctx, string title)
        {
            try
            {
                if (ctx.GetActiveTodosMethod?.Invoke(ctx.Manager, null) is System.Collections.IEnumerable todos)
                {
                    foreach (var todo in todos)
                    {
                        if (todo == null)
                            continue;
                        if (string.Equals(GetTodoTitle(todo), title, StringComparison.OrdinalIgnoreCase))
                            return GetTodoId(todo);
                    }
                }
            }
            catch (Exception ex)
            {
                Plugin.Log?.LogDebug($"[GiftingAssistant] FindActiveTodoIdByTitle: {ex.Message}");
            }

            return null;
        }

        private static bool IsOurGiftTodoForNpc(object todo, string npcName)
        {
            if (!IsOurTodo(todo))
                return false;
            return string.Equals(GetTodoTitle(todo), BuildTitle(npcName), StringComparison.OrdinalIgnoreCase);
        }

        // ---- task helpers --------------------------------------------------

        private static string BuildTitle(string npcName) => $"{TitlePrefix}{npcName}{TitleSuffix}";

        private static string BuildDescription(string giftNames)
        {
            return string.IsNullOrEmpty(giftNames)
                ? AutoMarker
                : $"{AutoMarker}. Preferred gifts: {giftNames}";
        }

        private static string ExtractNpcFromTitle(string title)
        {
            if (string.IsNullOrEmpty(title))
                return null;
            if (!title.StartsWith(TitlePrefix, StringComparison.OrdinalIgnoreCase) ||
                !title.EndsWith(TitleSuffix, StringComparison.OrdinalIgnoreCase))
                return null;

            int start = TitlePrefix.Length;
            int len = title.Length - TitlePrefix.Length - TitleSuffix.Length;
            return len > 0 ? title.Substring(start, len) : null;
        }

        /// <summary>Adds a gift task. Returns true when a task was actually added.</summary>
        private bool AddGiftTodo(TodoContext ctx, GiftTodoRequest request, bool skipIfExists)
        {
            string title = BuildTitle(request.NpcName);

            if (skipIfExists && HasActiveTodoWithTitle(ctx, title))
            {
                CacheTodoIdFromTitle(ctx, request.NpcName, title);
                return false;
            }

            var todoItemType = ctx.TodoItemType;
            var prioType = ctx.TodoPriorityType;
            var catType = ctx.TodoCategoryType;
            if (todoItemType == null || prioType == null || catType == null)
            {
                Plugin.Log?.LogWarning("[GiftingAssistant] Todo integration: Todo types not found");
                return false;
            }

            var item = Activator.CreateInstance(todoItemType);
            AccessTools.Property(todoItemType, "Title")?.SetValue(item, title);
            AccessTools.Property(todoItemType, "Description")?.SetValue(item, BuildDescription(request.GiftNames));
            AccessTools.Property(todoItemType, "Priority")?.SetValue(item, Enum.Parse(prioType, "Normal"));
            AccessTools.Property(todoItemType, "Category")?.SetValue(item, Enum.Parse(catType, "Social"));
            if (request.IconItemId > 0)
                AccessTools.Property(todoItemType, "IconItemId")?.SetValue(item, request.IconItemId);

            if (ctx.AddTodoMethod == null)
            {
                Plugin.Log?.LogWarning("[GiftingAssistant] Todo integration: AddTodo(TodoItem) not found");
                return false;
            }

            ctx.AddTodoMethod.Invoke(ctx.Manager, new[] { item });

            string id = GetTodoId(item);
            if (!string.IsNullOrEmpty(id))
            {
                string normalized = GiftGameData.NormalizeNpcName(request.NpcName);
                if (!string.IsNullOrEmpty(normalized))
                    _todoIdsByNpc[normalized] = id;
            }

            Plugin.Log?.LogInfo($"[GiftingAssistant] Pushed gift todo for {request.NpcName}");
            return true;
        }

        private void CacheTodoIdFromTitle(TodoContext ctx, string npcName, string title)
        {
            string id = FindOurGiftTodoIdByTitle(ctx, title);
            if (string.IsNullOrEmpty(id))
                return;

            string normalized = GiftGameData.NormalizeNpcName(npcName);
            if (!string.IsNullOrEmpty(normalized))
                _todoIdsByNpc[normalized] = id;
        }

        /// <summary>Removes every gift task we previously generated. Returns true if any were removed.</summary>
        private bool RemoveAllGiftTodos(TodoContext ctx)
        {
            if (ctx.RemoveTodoMethod == null)
                return false;

            var ids = new List<string>();
            foreach (var todo in EnumerateAllTodos(ctx))
            {
                if (todo == null || !IsOurTodo(todo))
                    continue;
                string id = GetTodoId(todo);
                if (!string.IsNullOrEmpty(id))
                    ids.Add(id);
            }

            foreach (string id in ids)
                ctx.RemoveTodoMethod.Invoke(ctx.Manager, new object[] { id });

            return ids.Count > 0;
        }

        private IEnumerable<object> EnumerateAllTodos(TodoContext ctx)
        {
            if (ctx.GetAllTodosMethod == null)
                yield break;

            if (!(ctx.GetAllTodosMethod.Invoke(ctx.Manager, null) is System.Collections.IEnumerable todos))
                yield break;

            var snapshot = new List<object>();
            foreach (var todo in todos)
                snapshot.Add(todo);

            foreach (var todo in snapshot)
                yield return todo;
        }

        private static bool IsOurTodo(object todo)
        {
            var desc = AccessTools.Property(todo.GetType(), "Description")?.GetValue(todo) as string;
            return !string.IsNullOrEmpty(desc) && desc.IndexOf(AutoMarker, StringComparison.OrdinalIgnoreCase) >= 0;
        }

        private static string GetTodoTitle(object todo) =>
            AccessTools.Property(todo.GetType(), "Title")?.GetValue(todo) as string;

        private static string GetTodoId(object todo) =>
            AccessTools.Property(todo.GetType(), "Id")?.GetValue(todo) as string;

        private static bool GetTodoCompleted(object todo) =>
            AccessTools.Property(todo.GetType(), "IsCompleted")?.GetValue(todo) is bool b && b;

        private bool HasActiveTodoWithTitle(TodoContext ctx, string title)
        {
            return !string.IsNullOrEmpty(FindActiveTodoIdByTitle(ctx, title));
        }

        // ---- context resolution -------------------------------------------

        private sealed class TodoContext
        {
            public object PluginInstance;
            public Type PluginType;
            public object Manager;
            public Type ManagerType;
            public Assembly Asm;
            public Type TodoItemType;
            public Type TodoPriorityType;
            public Type TodoCategoryType;
            public MethodInfo AddTodoMethod;
            public MethodInfo RemoveTodoMethod;
            public MethodInfo ToggleCompleteMethod;
            public MethodInfo GetTodoByIdMethod;
            public MethodInfo GetActiveTodosMethod;
            public MethodInfo GetAllTodosMethod;
        }

        private bool _warnedNoType;
        private bool _warnedNoManager;
        private bool _warnedNoData;

        private TodoContext TryGetContext()
        {
            if (_contextValid && _cachedContext != null)
            {
                if (_cachedContext.Manager != null &&
                    !(_cachedContext.Manager is UnityEngine.Object uo && uo == null))
                    return _cachedContext;
                InvalidateContext();
            }

            var pluginType = AccessTools.TypeByName("SunhavenTodo.Plugin");

            object pluginInstance = null;
            if (Chainloader.PluginInfos != null &&
                Chainloader.PluginInfos.TryGetValue(PluginGuid, out var info) && info != null)
            {
                var rawInstance = info.Instance;
                if (rawInstance != null)
                {
                    pluginInstance = rawInstance;
                    if (pluginType == null)
                        pluginType = rawInstance.GetType();
                }
            }

            if (pluginType == null)
            {
                if (!_warnedNoType)
                {
                    Plugin.Log?.LogWarning("[GiftingAssistant] Todo integration: SunhavenTodo.Plugin type not found");
                    _warnedNoType = true;
                }
                return null;
            }
            _warnedNoType = false;

            var getManager = AccessTools.Method(pluginType, "GetTodoManager", Type.EmptyTypes);
            var manager = getManager?.Invoke(null, null);
            if (manager == null)
            {
                if (!_warnedNoManager)
                {
                    Plugin.Log?.LogWarning("[GiftingAssistant] Todo integration: TodoManager unavailable");
                    _warnedNoManager = true;
                }
                return null;
            }
            _warnedNoManager = false;

            var managerType = manager.GetType();
            if (!EnsureTodoDataLoaded(pluginInstance, pluginType, manager, managerType))
                return null;

            var asm = pluginType.Assembly;
            _cachedContext = new TodoContext
            {
                PluginInstance = pluginInstance,
                PluginType = pluginType,
                Manager = manager,
                ManagerType = managerType,
                Asm = asm,
                TodoItemType = asm.GetType("SunhavenTodo.Data.TodoItem"),
                TodoPriorityType = asm.GetType("SunhavenTodo.Data.TodoPriority"),
                TodoCategoryType = asm.GetType("SunhavenTodo.Data.TodoCategory"),
                AddTodoMethod = AccessTools.Method(managerType, "AddTodo", new[] { asm.GetType("SunhavenTodo.Data.TodoItem") }),
                RemoveTodoMethod = AccessTools.Method(managerType, "RemoveTodo", new[] { typeof(string) }),
                ToggleCompleteMethod = AccessTools.Method(managerType, "ToggleComplete", new[] { typeof(string) }),
                GetTodoByIdMethod = AccessTools.Method(managerType, "GetTodoById", new[] { typeof(string) }),
                GetActiveTodosMethod = AccessTools.Method(managerType, "GetActiveTodos", Type.EmptyTypes),
                GetAllTodosMethod = AccessTools.Method(managerType, "GetAllTodos", Type.EmptyTypes)
            };
            _contextValid = true;
            return _cachedContext;
        }

        private bool EnsureTodoDataLoaded(object todoPluginInstance, Type pluginType, object manager, Type managerType)
        {
            if (HasTodoDataLoaded(manager, managerType))
            {
                _warnedNoData = false;
                return true;
            }

            string characterName = Plugin.GetManager()?.CurrentCharacter;
            if (string.IsNullOrEmpty(characterName))
                characterName = TryGetCharacterNameFromGameSave();

            if (string.IsNullOrEmpty(characterName))
            {
                if (!_warnedNoData)
                {
                    Plugin.Log?.LogWarning(
                        "[GiftingAssistant] Todo integration: no character loaded in Sun Haven Todo or Gifting Assistant yet");
                    _warnedNoData = true;
                }
                return false;
            }

            if (todoPluginInstance == null)
            {
                if (!_warnedNoData)
                {
                    Plugin.Log?.LogWarning(
                        "[GiftingAssistant] Todo integration: Sun Haven Todo data not loaded and its plugin instance is unavailable; will retry once data is loaded");
                    _warnedNoData = true;
                }
                return false;
            }

            var loadMethod = AccessTools.Method(pluginType, "LoadDataForCharacter", new[] { typeof(string) });
            if (loadMethod == null)
            {
                if (!_warnedNoData)
                {
                    Plugin.Log?.LogWarning("[GiftingAssistant] Todo integration: LoadDataForCharacter not found");
                    _warnedNoData = true;
                }
                return false;
            }

            loadMethod.Invoke(todoPluginInstance, new object[] { characterName });

            if (!HasTodoDataLoaded(manager, managerType))
            {
                if (!_warnedNoData)
                {
                    Plugin.Log?.LogWarning(
                        $"[GiftingAssistant] Todo integration: failed to load todo data for character \"{characterName}\"");
                    _warnedNoData = true;
                }
                return false;
            }

            _warnedNoData = false;
            return true;
        }

        private static bool HasTodoDataLoaded(object manager, Type managerType)
        {
            var currentCharacter = AccessTools.Property(managerType, "CurrentCharacter")?.GetValue(manager) as string;
            if (string.IsNullOrEmpty(currentCharacter))
                return false;

            var getData = AccessTools.Method(managerType, "GetData", Type.EmptyTypes);
            return getData?.Invoke(manager, null) != null;
        }

        private static void TrySaveTodoData(Type pluginType)
        {
            try
            {
                var saveMethod = AccessTools.Method(pluginType, "SaveData", Type.EmptyTypes);
                saveMethod?.Invoke(null, null);
            }
            catch (Exception ex)
            {
                Plugin.Log?.LogWarning($"[GiftingAssistant] Todo integration: SaveData failed: {ex.Message}");
            }
        }

        private static string TryGetCharacterNameFromGameSave()
        {
            try
            {
                var gameSaveType = AccessTools.TypeByName("Wish.GameSave");
                if (gameSaveType == null)
                    return null;

                var currentCharProp = AccessTools.Property(gameSaveType, "CurrentCharacter");
                var currentChar = currentCharProp?.GetValue(null);
                if (currentChar != null)
                {
                    var nameProp = AccessTools.Property(currentChar.GetType(), "characterName");
                    var name = nameProp?.GetValue(currentChar) as string;
                    if (!string.IsNullOrEmpty(name))
                        return name;
                }

                var instance = AccessTools.Property(gameSaveType, "Instance")?.GetValue(null);
                if (instance != null)
                {
                    var currentSave = AccessTools.Property(gameSaveType, "CurrentSave")?.GetValue(instance);
                    if (currentSave != null)
                    {
                        var charData = AccessTools.Property(currentSave.GetType(), "characterData")?.GetValue(currentSave);
                        if (charData != null)
                        {
                            var name = AccessTools.Property(charData.GetType(), "characterName")?.GetValue(charData) as string;
                            if (!string.IsNullOrEmpty(name))
                                return name;
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Plugin.Log?.LogWarning($"[GiftingAssistant] Todo integration: character lookup failed: {ex.Message}");
            }

            return null;
        }
    }
}
