using System;
using System.Collections.Generic;
using GiftingAssistant.Data;
using GiftingAssistant.Game;
using SunhavenMods.Shared;

namespace GiftingAssistant.Integration
{
    /// <summary>
    /// A request to publish (or refresh) a single "gift X today" task in Sun Haven Todo.
    /// The caller resolves the icon/gift names so this bridge stays UI-agnostic.
    /// </summary>
    public sealed class GiftTodoRequest
    {
        public string NpcName { get; }
        public int IconItemId { get; }
        public string GiftNames { get; }

        public GiftTodoRequest(string npcName, int iconItemId, string giftNames)
        {
            NpcName = npcName;
            IconItemId = iconItemId;
            GiftNames = giftNames ?? "";
        }
    }

    /// <summary>
    /// Gift tasks in Sun Haven Todo, through <see cref="TodoSoftClient"/>.
    /// Click handlers queue work here; <see cref="ProcessPending"/> flushes once per frame
    /// (batched save, no full-roster scan on every button press).
    /// </summary>
    public sealed class TodoIntegration
    {
        /// <summary>Stable marker placed in every task description so we only touch our own todos.</summary>
        private const string AutoMarker = "Auto-generated by Gifting Assistant";
        private const string TitlePrefix = "Gift ";
        private const string TitleSuffix = " today";

        private bool _availableCached;

        /// <summary>True when Sun Haven Todo is loaded via Chainloader.</summary>
        public bool IsAvailable
        {
            get
            {
                if (_availableCached)
                    return true;
                _availableCached = TodoSoftClient.IsAvailable;
                return _availableCached;
            }
        }

        /// <summary>When false, the gifting window uses its own roster only (no +Todo button).</summary>
        public bool IsEnabled { get; set; }

        /// <summary>True when ReminderMode is PushToTodo and Sun Haven Todo is loaded.</summary>
        public bool CanPushTodos => IsAvailable && IsEnabled;

        // Cached todo ids (normalized NPC name -> todo id) for O(1) complete/remove.
        private readonly Dictionary<string, string> _todoIdsByNpc =
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        private readonly HashSet<string> _pendingPublish = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        private readonly Dictionary<string, bool> _pendingComplete = new Dictionary<string, bool>(StringComparer.OrdinalIgnoreCase);
        private readonly HashSet<string> _pendingRemove = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        private bool _pendingEnsureAll;
        private bool _pendingRefreshDaily;
        private bool _flushScheduled;

        /// <summary>Queue a single NPC gift task ( +Todo button ). Resolves gifts on flush.</summary>
        public void QueuePublish(GiftRosterEntry entry)
        {
            if (!CanPushTodos || entry == null || string.IsNullOrEmpty(entry.NpcName))
                return;
            _pendingPublish.Add(entry.NpcName);
            _pendingRemove.Remove(entry.NpcName);
            ScheduleFlush();
        }

        /// <summary>Queue completion sync for one NPC (gifted toggle / in-game gift).</summary>
        public void QueueComplete(string npcName, bool completed)
        {
            if (!CanPushTodos || string.IsNullOrEmpty(npcName))
                return;
            _pendingComplete[npcName] = completed;
            ScheduleFlush();
        }

        /// <summary>Queue removal of one NPC's gift task (roster remove).</summary>
        public void QueueRemove(string npcName)
        {
            if (!CanPushTodos || string.IsNullOrEmpty(npcName))
                return;
            _pendingRemove.Add(npcName);
            _pendingPublish.Remove(npcName);
            _pendingComplete.Remove(npcName);
            ScheduleFlush();
        }

        /// <summary>Queue ensure-all (character load). Not called from click handlers.</summary>
        public void QueueEnsureAll()
        {
            if (!CanPushTodos)
                return;
            _pendingEnsureAll = true;
            ScheduleFlush();
        }

        /// <summary>Queue daily refresh (new day). Not called from click handlers.</summary>
        public void QueueRefreshDaily()
        {
            if (!CanPushTodos)
                return;
            _pendingRefreshDaily = true;
            ScheduleFlush();
        }

        /// <summary>Legacy immediate API — forwards to queue.</summary>
        public void PublishGiftTodo(GiftTodoRequest request)
        {
            if (request == null || string.IsNullOrEmpty(request.NpcName))
                return;
            _pendingPublish.Add(request.NpcName);
            ScheduleFlush();
        }

        /// <summary>Legacy immediate API — forwards to queue.</summary>
        public void EnsureGiftTodos(IList<GiftTodoRequest> requests)
        {
            QueueEnsureAll();
        }

        /// <summary>Legacy immediate API — forwards to queue.</summary>
        public void RefreshDailyGiftTodos(IList<GiftTodoRequest> requests)
        {
            QueueRefreshDaily();
        }

        /// <summary>Legacy immediate API — forwards to queue.</summary>
        public void CompleteGiftTodo(string npcName, bool completed)
        {
            QueueComplete(npcName, completed);
        }

        /// <summary>Drop tracked ids (character change / daily refresh).</summary>
        public void ResetTracking()
        {
            _todoIdsByNpc.Clear();
            _pendingPublish.Clear();
            _pendingComplete.Clear();
            _pendingRemove.Clear();
            _pendingEnsureAll = false;
            _pendingRefreshDaily = false;
            _flushScheduled = false;
        }

        /// <summary>Process queued todo work. Call once per frame from PersistentRunner.</summary>
        public void ProcessPending()
        {
            if (!_flushScheduled || !CanPushTodos)
                return;

            _flushScheduled = false;

            if (_pendingRemove.Count == 0 && _pendingPublish.Count == 0 && _pendingComplete.Count == 0 &&
                !_pendingEnsureAll && !_pendingRefreshDaily)
                return;

            try
            {
                var todo = TodoSoftClient.TryGetManagerForCharacter(ResolveTodoCharacterName(), Plugin.Log);
                if (todo == null)
                {
                    ScheduleFlush();
                    return;
                }

                bool changed = false;

                if (_pendingRefreshDaily)
                {
                    _pendingRefreshDaily = false;
                    changed |= RemoveAllGiftTodos(todo);
                    _todoIdsByNpc.Clear();
                    changed |= EnsureAllFromRoster(todo);
                }
                else
                {
                    if (_pendingEnsureAll)
                    {
                        _pendingEnsureAll = false;
                        changed |= EnsureAllFromRoster(todo);
                    }

                    foreach (string npc in _pendingRemove)
                        changed |= RemoveGiftTodoForNpc(todo, npc);
                    _pendingRemove.Clear();

                    foreach (string npc in _pendingPublish)
                    {
                        changed |= RemoveGiftTodoForNpc(todo, npc);
                        changed |= PublishForNpc(todo, npc, skipIfExists: false);
                    }
                    _pendingPublish.Clear();

                    foreach (var kvp in _pendingComplete)
                        changed |= CompleteForNpc(todo, kvp.Key, kvp.Value);
                    _pendingComplete.Clear();
                }

                if (changed)
                    TodoSoftClient.Save(Plugin.Log);
            }
            catch (Exception ex)
            {
                Plugin.Log?.LogWarning($"[GiftingAssistant] Todo flush failed: {ex.Message}");
                ScheduleFlush();
            }
        }

        private void ScheduleFlush()
        {
            _flushScheduled = true;
        }

        private bool EnsureAllFromRoster(TodoManagerReflection todo)
        {
            bool changed = false;
            var manager = Plugin.GetManager();
            if (manager == null)
                return false;

            foreach (var entry in manager.GetEntries())
            {
                if (entry == null || string.IsNullOrEmpty(entry.NpcName))
                    continue;
                changed |= PublishForNpc(todo, entry.NpcName, skipIfExists: true);
            }

            return changed;
        }

        private bool PublishForNpc(TodoManagerReflection todo, string npcName, bool skipIfExists = true)
        {
            var entry = Plugin.GetManager()?.GetEntry(npcName);
            if (entry == null)
                return false;

            GiftSuggestionResolver.RefreshPrimaryIconForNpc(npcName);
            int iconId = GiftSuggestionResolver.ResolvePrimaryIconId(entry, forceRefresh: true);
            string names = GiftSuggestionResolver.ResolveGiftNames(entry, 3);
            return AddGiftTodo(todo, new GiftTodoRequest(entry.NpcName, iconId, names), skipIfExists);
        }

        private bool CompleteForNpc(TodoManagerReflection todo, string npcName, bool completed)
        {
            string normalized = GiftGameData.NormalizeNpcName(npcName);
            if (string.IsNullOrEmpty(normalized))
                return false;

            string todoId = FindTodoIdForNpc(todo, normalized, npcName);
            if (string.IsNullOrEmpty(todoId))
                return false;

            if (todo.IsCompleted(todoId) == null)
            {
                _todoIdsByNpc.Remove(normalized);
                return false;
            }

            return todo.SetCompleted(todoId, completed);
        }

        private bool RemoveGiftTodoForNpc(TodoManagerReflection todo, string npcName)
        {
            string normalized = GiftGameData.NormalizeNpcName(npcName);
            string todoId = FindTodoIdForNpc(todo, normalized, npcName);
            if (string.IsNullOrEmpty(todoId))
                return false;

            todo.RemoveTodo(todoId);
            _todoIdsByNpc.Remove(normalized);
            return true;
        }

        private string FindTodoIdForNpc(TodoManagerReflection todo, string normalized, string displayName)
        {
            if (_todoIdsByNpc.TryGetValue(normalized, out string cached) && !string.IsNullOrEmpty(cached))
            {
                var existing = todo.GetById(cached);
                if (existing != null && IsOurGiftTodoForNpc(existing, displayName))
                    return cached;

                _todoIdsByNpc.Remove(normalized);
            }

            string id = FindTodoIdByTitle(todo, BuildTitle(displayName), activeOnly: false);
            if (!string.IsNullOrEmpty(id))
                _todoIdsByNpc[normalized] = id;
            return id;
        }

        /// <summary>
        /// Id of a todo with this title. All todos must also carry our marker; active-only matches
        /// any active todo with the title so a hand-made copy still counts as "already exists".
        /// </summary>
        private static string FindTodoIdByTitle(TodoManagerReflection todo, string title, bool activeOnly)
        {
            foreach (var item in todo.GetTodos(activeOnly))
            {
                if (!activeOnly && !IsOurTodo(item))
                    continue;
                if (string.Equals(item.Title, title, StringComparison.OrdinalIgnoreCase))
                    return item.Id;
            }

            return null;
        }

        private static bool IsOurGiftTodoForNpc(TodoSnapshot item, string npcName)
        {
            return IsOurTodo(item) &&
                   string.Equals(item.Title, BuildTitle(npcName), StringComparison.OrdinalIgnoreCase);
        }

        // ---- task helpers --------------------------------------------------

        private static string BuildTitle(string npcName) => $"{TitlePrefix}{npcName}{TitleSuffix}";

        private static string BuildDescription(string giftNames)
        {
            return string.IsNullOrEmpty(giftNames)
                ? AutoMarker
                : $"{AutoMarker}. Preferred gifts: {giftNames}";
        }

        /// <summary>Adds a gift task. Returns true when a task was actually added.</summary>
        private bool AddGiftTodo(TodoManagerReflection todo, GiftTodoRequest request, bool skipIfExists)
        {
            string title = BuildTitle(request.NpcName);
            string normalized = GiftGameData.NormalizeNpcName(request.NpcName);

            if (skipIfExists && !string.IsNullOrEmpty(FindTodoIdByTitle(todo, title, activeOnly: true)))
            {
                string existingId = FindTodoIdByTitle(todo, title, activeOnly: false);
                if (!string.IsNullOrEmpty(existingId) && !string.IsNullOrEmpty(normalized))
                    _todoIdsByNpc[normalized] = existingId;
                return false;
            }

            string id = todo.AddTodo(new TodoDraft
            {
                Title = title,
                Description = BuildDescription(request.GiftNames),
                Priority = "Normal",
                Category = "Social",
                IconItemId = request.IconItemId
            });

            if (!string.IsNullOrEmpty(id) && !string.IsNullOrEmpty(normalized))
                _todoIdsByNpc[normalized] = id;

            Plugin.Log?.LogInfo($"[GiftingAssistant] Pushed gift todo for {request.NpcName}");
            return true;
        }

        /// <summary>Removes every gift task we previously generated. Returns true if any were removed.</summary>
        private static bool RemoveAllGiftTodos(TodoManagerReflection todo)
        {
            bool removed = false;
            foreach (var item in todo.GetTodos(activeOnly: false))
            {
                if (IsOurTodo(item))
                    removed |= todo.RemoveTodo(item.Id);
            }

            return removed;
        }

        private static bool IsOurTodo(TodoSnapshot item) =>
            item.Description.IndexOf(AutoMarker, StringComparison.OrdinalIgnoreCase) >= 0;

        private static string ResolveTodoCharacterName()
        {
            string characterName = Plugin.GetManager()?.CurrentCharacter;
            if (string.IsNullOrEmpty(characterName))
            {
                characterName = GameSaveCharacterName.TryGetCurrent(
                    null,
                    msg => Plugin.Log?.LogWarning($"[GiftingAssistant] Todo integration: character lookup failed: {msg}"));
            }

            return characterName;
        }
    }
}
