# Creates Localization/strings.json for all UI mods (en source + all 16 langs).
# Non-English defaults to English; run fill-localization-languages.ps1 -Translate for MT pass.
$ErrorActionPreference = "Stop"
$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$Langs = @("en","da","de","es","fr","it","ja","ko","nl","pt","pt-BR","ru","sv","zh-CN","zh-TW","uk")

function Write-ModStrings {
    param([string]$ModFolder, [hashtable]$Entries)
    $dir = Join-Path (Join-Path $RepoRoot $ModFolder) "Localization"
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
    $root = [ordered]@{}
    foreach ($key in ($Entries.Keys | Sort-Object)) {
        $en = [string]$Entries[$key]
        $obj = [ordered]@{ en = $en }
        foreach ($lang in $Langs) {
            if ($lang -ne "en") { $obj[$lang] = $en }
        }
        $root[$key] = $obj
    }
    $path = Join-Path $dir "strings.json"
    ($root | ConvertTo-Json -Depth 6) | Set-Content -Path $path -Encoding UTF8
    Write-Host "Wrote $path ($($Entries.Count) keys)"
}

# --- Sunhaven Todo ---
Write-ModStrings "SunhavenTodo" @{
    "todo.header.title" = "Todo List"
    "todo.button.sticky" = "Sticky"
    "todo.button.sticky.tooltip" = "Show the movable sticky task panel (top tasks)"
    "todo.button.add" = "+ Add"
    "todo.button.cancel" = "Cancel"
    "todo.stats.active" = "Active: {0}"
    "todo.stats.completed" = "Completed: {0}"
    "todo.stats.total" = "Total: {0}"
    "todo.filter.search" = "Search:"
    "todo.filter.showDone.on" = "[v] Show Done"
    "todo.filter.showDone.off" = "[ ] Show Done"
    "todo.filter.clearDone" = "Clear Done"
    "todo.tab.all" = "All"
    "todo.list.empty" = "No tasks to show"
    "todo.item.noTitle" = "(No title)"
    "todo.form.editTitle" = "Edit Task"
    "todo.form.addTitle" = "Add New Task"
    "todo.form.titleLabel" = "Title:"
    "todo.form.descLabel" = "Description (optional):"
    "todo.form.priorityLabel" = "Priority:"
    "todo.form.categoryLabel" = "Category:"
    "todo.form.recurring" = " Recurring task"
    "todo.form.resets" = "Resets:"
    "todo.form.update" = "Update"
    "todo.form.addTask" = "Add Task"
    "todo.footer.hint" = "Press ESC to close | Drag header to move"
    "todo.hud.title" = "Todo ({0})"
    "todo.hud.openHint" = "{0} to open"
    "todo.hud.dragHint" = "drag to move"
    "todo.hud.empty" = "No active tasks"
    "todo.priority.Low" = "Low"
    "todo.priority.Normal" = "Normal"
    "todo.priority.High" = "High"
    "todo.priority.Urgent" = "Urgent"
    "todo.category.General" = "General"
    "todo.category.Farming" = "Farming"
    "todo.category.Mining" = "Mining"
    "todo.category.Fishing" = "Fishing"
    "todo.category.Combat" = "Combat"
    "todo.category.Crafting" = "Crafting"
    "todo.category.Social" = "Social"
    "todo.category.Quests" = "Quests"
    "todo.category.Collection" = "Collection"
    "todo.recur.Daily" = "Daily"
    "todo.recur.Weekly" = "Weekly"
    "todo.recur.Seasonal" = "Seasonal"
}

# --- Birthday Reminder ---
Write-ModStrings "BirthdayReminder" @{
    "birthday.hud.title.one" = "Birthday Today!"
    "birthday.hud.title.many" = "Birthdays Today!"
    "birthday.hud.noBirthdays" = "No birthdays today"
    "birthday.hud.gifts" = "Gifts"
    "birthday.gift.title" = "{0}'s Gifts"
    "birthday.gift.loved" = "Loved Gifts"
    "birthday.gift.liked" = "Liked Gifts"
    "birthday.gift.universal" = "Universal Gifts"
}

# --- Crop Optimizer ---
Write-ModStrings "CropOptimizer" @{
    "crop.hud.title" = "Crop Optimizer"
    "crop.hud.tracked" = "Tracked crops: <b>{0}</b>"
    "crop.hud.projected" = "Projected sell: <color=#F7D982><b>{0:N0}g</b></color>"
    "crop.hud.tooltipToggle.on" = "Toggle Crop Tooltips <color=#B8A078>(on)</color>"
    "crop.hud.tooltipToggle.off" = "Toggle Crop Tooltips <color=#B8A078>(off)</color>"
    "crop.tooltip.headerTag.ready" = "ready to harvest"
    "crop.tooltip.crop" = "Crop"
    "crop.tooltip.itemId" = "Item #{0}"
    "crop.tooltip.quality" = "Quality: <b>{0}</b> <color={1}>(×{2:0.##})</color>"
    "crop.tooltip.growth" = "Growth: <b>{0}</b>"
    "crop.tooltip.readyIn" = "Ready in <b><color={0}>~{1:0.#} h</color></b>"
    "crop.tooltip.readyInCached" = "Ready in <b><color={0}>~{1:0.#} h</color></b> <color={2}>(cached)</color>"
    "crop.tooltip.fertilized" = "<b>Fertilized</b>"
    "crop.tooltip.notFertilized" = "Not fertilized"
    "crop.water.unknown" = "Water: <color=#B8A078>unknown</color>"
    "crop.water.hoedDry" = "Hoed <color=#B8A078>(dry - needs water)</color>"
    "crop.water.label" = "Water: {0}"
}

# --- Senpai's Chest ---
Write-ModStrings "SenpaisChest" @{
    "chest.config.title" = "Senpai's Chest Config"
    "chest.section.rules" = "Item Rules"
    "chest.rules.none" = "  No rules configured. Add rules below."
    "chest.section.addRule" = "Add New Rule"
    "chest.presets" = "Presets"
    "chest.preset.equipment" = "Equipment"
    "chest.preset.consumables" = "Consumables"
    "chest.preset.crafting" = "Crafting"
    "chest.manageGroups" = "Manage Groups"
    "chest.addRule" = "Add Rule"
    "chest.removeSmartChest" = "Remove Smart Chest"
    "chest.close" = "Close"
    "chest.summary" = "Summary"
    "chest.summary.rules" = "Rules: {0} | Status: {1}"
    "chest.summary.accepts" = "Accepts:"
    "chest.tips.header" = "Tips"
    "chest.tips.filter" = "• Rules filter auto-sort. Multiple = AND."
    "chest.tips.transfer" = "• Transfer SAME/ALL applies rules."
    "chest.tips.wildcard" = "• Wildcard name rule: * = any chars, ? = one char."
    "chest.tips.wildcardGroups" = "• Add wildcard patterns in Manage Groups (* = any chars, ? = one char)."
    "chest.groups.intro" = "Create or edit groups. Add item IDs and wildcard name patterns here, then use 'By Group' rules on chests."
    "chest.groups.new" = "New Group"
    "chest.groups.header" = "Groups:"
    "chest.groups.editing" = "Editing: {0}"
    "chest.groups.noItems" = "  No items. Search below to add."
    "chest.groups.wildcardPatterns" = "Wildcard patterns:"
    "chest.groups.addIds" = "+IDs"
    "chest.groups.addItemSearch" = "Add item (search):"
    "chest.groups.addWildcard" = "Add wildcard pattern (* / ?):"
    "chest.groups.wildcardExamples" = "Examples: Tomato*  |  *Ore  |  Gold ???"
    "chest.groups.addPattern" = "Add Pattern"
    "chest.groups.addMatchesToIds" = "Add Matches to IDs"
    "chest.rule.search" = "Search:"
    "chest.rule.selected" = "Selected: {0}"
    "chest.rule.noItemsFound" = "  No items found."
    "chest.rule.category" = "Category:"
    "chest.rule.itemType" = "Item Type:"
    "chest.rule.property" = "Property:"
    "chest.rule.group" = "Group:"
    "chest.rule.noGroups" = "  No groups yet. Click Manage Groups to create one."
    "chest.rule.wildcardManaged" = "Wildcard rules are managed via Manage Groups."
    "chest.rule.wildcardByGroup" = "Add patterns to a group, then add a By Group rule."
    "chest.rule.namePattern" = "Item name pattern:"
    "chest.rule.namePatternExamples" = "  Examples: Tomato*, *Ore, Gold ???  (letters match any case)"
}

# --- The Vault ---
Write-ModStrings "TheVault" @{
    "vault.title" = "✧  The Vault  ✧"
    "vault.subtitle" = "Currency Storage System"
    "vault.debug.disabledHint" = "Withdraw / sweep are disabled in Debug view. Turn off Debug in Settings to use them."
    "vault.close" = "Close"
    "vault.tab.debug" = "‼ Debug"
    "vault.tab.settings" = "⚙ Settings"
    "vault.notInitialized" = "(Vault not initialized)"
    "vault.debug.intro" = "Raw snapshot of all vault dictionaries (Seasonal, Community, Keys, Tickets, Orbs, Custom)."
    "vault.empty.custom" = "No custom currencies yet."
    "vault.hint.custom" = "Other mods register entries with TheVault.Api.VaultIntegration.RegisterCustomCurrency (after The Vault loads)."
    "vault.hint.customId" = "Use a short id (a-z, 0-9, underscore) and optional Sun Haven item id for withdraw / auto-deposit."
    "vault.empty.seasonal" = "No seasonal tokens in the vault."
    "vault.hint.seasonal" = "Deposit festival tokens from your inventory, or enable auto-deposit for those items."
    "vault.empty.keys" = "No keys stored in the vault."
    "vault.hint.keys" = "Keys you move into the vault appear here. Use Sweep or per-item auto-deposit to add them."
    "vault.empty.special" = "No special currencies in the vault."
    "vault.hint.special" = "Doubloons, tickets, shards, and similar currencies show here once deposited."
    "vault.empty.category" = "No items in this category"
    "vault.settings.title" = "⚙  Settings (saved to config file)"
    "vault.settings.display" = "Display"
    "vault.settings.windowScale" = "Window scale:"
    "vault.settings.hud" = "HUD"
    "vault.settings.hudDragHint" = "Drag the currency bar by its top strip to move it; position saves to config (like Sun Haven Todo). Changing [HUD] Position resets a custom placement."
    "vault.settings.hudScale" = "HUD scale:"
    "vault.settings.hudDensity" = "HUD density:"
    "vault.settings.debug" = "Debug (full vault inspector)"
    "vault.settings.openVault" = "Open Vault"
    "vault.settings.key" = "Key:"
    "vault.settings.altKey" = "Alt key:"
    "vault.settings.autoSave" = "Changes save automatically."
    "vault.row.hint" = "Click a row to select, or use quick withdraw / deposit buttons"
    "vault.qty" = "Qty:"
    "vault.withdraw" = "Withdraw"
    "vault.deposit" = "Deposit"
    "vault.inBag" = "In inventory (bag): {0}"
    "vault.noDeposit" = 'No matching inventory item for this row - deposit is unavailable.'
    "vault.sweep" = "Sweep Inventory (Auto-Deposit Now)"
}

# --- Haven's Almanac ---
Write-ModStrings "HavensAlmanac" @{
    "almanac.dashboard.title" = "Haven's Almanac - Dashboard"
    "almanac.dashboard.noMods" = "No supported companion mods detected."
    "almanac.dashboard.installHint" = "Install any of: SunhavenTodo, Birthday Reminder, Museum Tracker, Senpai's Chest, The Vault, Haven's Birthright, Haven Dev Tools, or Crop Optimizer."
    "almanac.dashboard.refreshError" = "[!] Last refresh error: {0}"
    "almanac.briefing.title" = "Good Morning!"
    "almanac.briefing.empty" = "Nothing noteworthy today. Have a great day!"
    "almanac.briefing.dismiss" = "Dismiss"
    "almanac.hud.title" = "Haven's Almanac"
    "almanac.hud.noMods" = "No supported mods detected"
    "almanac.hud.installHint" = "Install SunhavenTodo, Birthday, Museum, Vault, Chests, Birthright, DevTools, or CropOptimizer"
    "almanac.dashboard.error" = "Error: {0}"
    "almanac.provider.birthday.noBirthdays" = "No birthdays today."
    "almanac.provider.birthday.todayList" = "Today's Birthdays ({0}):"
    "almanac.provider.birthday.gifted" = " [Gifted]"
    "almanac.provider.birthday.notGifted" = " [Not gifted]"
    "almanac.provider.birthday.briefing" = "  It's {0}'s birthday!{1}"
    "almanac.provider.birthday.giftedBriefing" = " (gifted)"
    "almanac.provider.birthday.reminder" = "  Don't forget to bring a gift!"
    "almanac.provider.vault.empty" = "Vault is empty."
    "almanac.provider.vault.stored" = "Stored Currencies ({0}):"
    "almanac.provider.vault.more" = "  ... and {0} more"
    "almanac.provider.vault.briefing" = "Vault holds {0} currenc{1}."
    "almanac.provider.todo.stats" = "Total: {0}  |  Completed: {1}  |  Active: {2}"
    "almanac.provider.todo.percent" = "{0}% complete"
    "almanac.provider.todo.highPriority" = "High Priority Tasks:"
    "almanac.provider.todo.briefing.active" = "You have {0} active task{1}."
    "almanac.provider.todo.briefing.high" = "  {0} {1} high priority!"
    "almanac.provider.birthright.race" = "Race: {0}"
    "almanac.provider.birthright.noBonuses" = "No active bonuses."
    "almanac.provider.birthright.activeBonuses" = "Active Bonuses ({0}):"
    "almanac.provider.crop.topHeader" = "Top crops by projected value:"
    "almanac.provider.crop.topRow" = "  {0}. {1} — {2}g ({3} plant{4})"
    "almanac.provider.museum.donated" = "Donated: {0} / {1}"
    "almanac.provider.museum.percent" = "{0:F1}% complete"
    "almanac.provider.museum.needed" = "{0} items still needed"
    "almanac.provider.museum.briefing.summary" = "Museum: {0:F0}% complete ({1}/{2})"
    "almanac.provider.museum.briefing.left" = "  Only {0} item{1} left!"
    "almanac.provider.chest.count" = "Configured Smart Chests: {0}"
    "almanac.provider.devtools.status" = "Status: {0}"
    "almanac.provider.devtools.authorized" = "Authorized"
    "almanac.provider.devtools.notAuthorized" = "Not Authorized"
    "almanac.provider.devtools.player" = "Player: {0}"
    "almanac.provider.health.empty" = "No VersionChecker telemetry yet."
}

# --- S.M.U.T. ---
Write-ModStrings "SunHavenMuseumUtilityTracker" @{
    "smut.title" = "S.M.U.T."
    "smut.subtitle" = "Sun Haven Museum Utility Tracker"
    "smut.search" = "Search"
    "smut.clear" = "Clear"
    "smut.sync" = "Sync with Game"
    "smut.empty.search" = "No items match ""{0}"""
    "smut.empty.donated" = "All items in this section are donated!"
    "smut.item.donated" = "Donated"
    "smut.item.needed" = "Needed"
}

# --- Haven Dev Tools ---
Write-ModStrings "HavenDevTools" @{
    "devtools.title" = "Haven Dev Tools"
    "devtools.player" = "Player: {0}"
    "devtools.mod.thevault" = "TheVault: {0}"
    "devtools.mod.smut" = "SMUT: {0}"
    "devtools.mod.birthright" = "Birthright: {0}"
    "devtools.mod.senpai" = "Senpai: {0}"
    "devtools.mod.todo" = "Todo: {0}"
    "devtools.yes" = "Yes"
    "devtools.no" = "No"
    "devtools.close" = "Close (Esc)"
    "devtools.extensions" = "Extensions"
    "devtools.extensions.none" = 'No extension panels registered. Mods can implement IDevToolsPanel and call DevToolsRegistry.Register() to add panels here.'
    "devtools.console.title" = "Command Console"
    "devtools.console.hint" = "Type commands and press Enter. Supported: spawn, tp, time.set, reload.config"
    "devtools.console.init" = "(Console service initializing...)"
    "devtools.log.title" = "Log Viewer"
    "devtools.log.init" = "(Log viewer initializing...)"
    "devtools.perf.title" = "Performance"
    "devtools.perf.fps" = "FPS: {0:F1}"
    "devtools.perf.memory" = "Memory: {0:F1} MB"
    "devtools.perf.overlayHint" = "(Also shown in overlay when ShowPerformance is enabled)"
    "devtools.items.title" = "Item Inspector"
    "devtools.items.held" = "Held: {0} ({1})"
    "devtools.items.heldNone" = "Held: None"
    "devtools.search" = "Search:"
    "devtools.clear" = "Clear"
    "devtools.selected" = "Selected: {0}"
    "devtools.items.notFound" = "No items found."
    "devtools.spawn" = "Spawn:"
    "devtools.spawn.id" = "ID:"
    "devtools.spawn.qty" = "Qty:"
    "devtools.spawn.toInventory" = "Spawn to Inventory"
    "devtools.spawn.one" = "Spawn 1"
    "devtools.currency.title" = "Currency Tracker"
    "devtools.currency.unavailable" = "Currency tracker not available"
    "devtools.currency.gold" = "Gold: {0:N0}"
    "devtools.currency.orbs" = "Orbs: {0:N0}"
    "devtools.currency.tickets" = "Tickets: {0:N0}"
    "devtools.currency.inventory" = "Inventory Currencies:"
    "devtools.currency.none" = "  (none)"
    "devtools.currency.vault" = "Vault Currencies:"
    "devtools.currency.vaultEmpty" = "  (vault empty)"
    "devtools.currency.vaultMissing" = "(The Vault not installed)"
    "devtools.museum.title" = "Museum Bundle Inspector"
    "devtools.museum.notInstalled" = "S.M.U.T. not installed"
    "devtools.museum.unavailable" = "Bundle inspector not available"
    "devtools.museum.character" = "Character: {0}"
    "devtools.museum.progress" = 'Progress: {0}/{1} ({2:F1}%)'
    "devtools.museum.notLoaded" = "Donation data not loaded"
    "devtools.museum.noData" = "No museum data available"
    "devtools.museum.section" = "Section:"
    "devtools.museum.bundle" = "Bundle:"
    "devtools.museum.itemsIn" = "Items in {0}:"
    "devtools.museum.spawn" = "Spawn{0}"
    "devtools.museum.idInAssets" = "(ID in Unity assets)"
    "devtools.race.title" = "Race Modifier Tracker"
    "devtools.race.unavailable" = "Race tracker not available"
    "devtools.race.current" = "Current Race: {0}"
    "devtools.race.bonuses" = "Active Bonuses:"
    "devtools.race.noBonuses" = "  (no bonuses active)"
    "devtools.race.birthrightMissing" = "Haven's Birthright not installed"
    "devtools.race.browse" = "Browse Race Bonuses:"
    "devtools.race.noDefined" = "  (no bonuses defined)"
    "devtools.utility" = "Utility"
    "devtools.config" = "Config:"
    "devtools.config.reload" = "Reload HavenDevTools Config"
    "devtools.logging" = "Logging:"
    "devtools.logCurrencyIds" = "Log All Currency IDs"
    "devtools.logPlayerStats" = "Log Player Stats"
    "devtools.auth.title" = "Authorization Hash Generator:"
    "devtools.auth.hint" = "Use this to generate hashes for new authorized Steam IDs"
    "devtools.auth.logHash" = "Log Current Steam ID Hash"
    "devtools.versions.title" = "Version Checker:"
    "devtools.versions.checking" = "Checking..."
    "devtools.versions.checkAll" = "Check All Mod Versions"
    "devtools.versions.testNotify" = "Test Notification"
    "devtools.versions.update" = "Update: v{0}"
    "devtools.versions.upToDate" = "Up to date"
    "devtools.versions.notChecked" = "Not checked"
    "devtools.log.level" = "Level:"
    "devtools.log.export" = "Export"
    "devtools.overlay.title" = "Haven Dev Tools"
    "devtools.overlay.keys" = "F11: Window | F6: Toggle"
    "devtools.overlay.player" = "Player:"
    "devtools.overlay.race" = "Race:"
    "devtools.overlay.gold" = "Gold:"
    "devtools.overlay.position" = "Position:"
    "devtools.overlay.held" = "Held:"
    "devtools.tab.tools" = "Tools"
    "devtools.tab.azraels_mods" = "Azrael's Mods"
    "devtools.tab.extensions" = "Extensions"
    "devtools.tab.items" = "Items"
    "devtools.tab.currencies" = "Currencies"
    "devtools.tab.console" = "Console"
    "devtools.tab.log" = "Log"
    "devtools.tab.perf" = "Perf"
    "devtools.tab.utility" = "Utility"
    "devtools.console.output" = "Output:"
    "devtools.console.execute" = "Execute"
    "devtools.console.commands" = "Commands: spawn <id> [qty] | tp <scene> | time.set <hour> | reload.config"
    "azrael.none_detected" = "No Azrael's mods detected. Install SenpaisChest, TheVault, S.M.U.T., Birthright, Birthday Reminder, Todo, Almanac, or Trinket Fortune."
    "azrael.tab.senpais_chest" = "Senpai's Chest"
    "azrael.tab.the_vault" = "The Vault"
    "azrael.tab.smut" = "S.M.U.T."
    "azrael.tab.birthright" = "Birthright"
    "azrael.tab.birthday" = "Birthday"
    "azrael.tab.todo" = "Todo"
    "azrael.tab.almanac" = "Almanac"
    "azrael.tab.trinket_fortune" = "Trinket Fortune"
    "azrael.senpai.title" = "Senpai's Chest"
    "azrael.senpai.trigger_scan" = "Trigger Manual Scan"
    "azrael.vault.title" = "The Vault"
    "azrael.vault.currencies" = "Vault Currencies:"
    "azrael.vault.empty" = "  (vault empty or not loaded)"
    "azrael.vault.inspector_toggle" = " Full vault inspector (zeros + Debug tab + full HUD)"
    "azrael.vault.inspector_hint" = "Moved from The Vault settings; persists in com.azraelgodking.havendevtools.cfg ([The Vault] section)."
    "azrael.smut.title" = "S.M.U.T. - Museum Bundle Inspector"
    "azrael.birthright.title" = "Haven's Birthright - Race Modifier Tracker"
    "azrael.birthright.active_bonuses" = "Active Bonuses:"
    "azrael.birthday.title" = "Birthday Reminder"
    "azrael.birthday.check" = "Check Birthdays"
    "azrael.birthday.refresh" = "Manual Refresh"
    "azrael.birthday.test_notify" = "Send All Test Notifications"
    "azrael.todo.title" = "Sunhaven Todo"
    "azrael.todo.toggle_ui" = "Toggle UI"
    "azrael.todo.toggle_hud" = "Toggle HUD"
    "azrael.todo.save" = "Save Data"
    "azrael.almanac.title" = "Haven's Almanac"
    "azrael.almanac.refresh" = "Refresh All"
    "azrael.trinket.not_loaded" = "Trinket Fortune not loaded."
}

# --- Haven's Respec ---
Write-ModStrings "HavensRespec" @{
    "respec.button.reset" = "Reset"
    "respec.button.undo" = "Undo"
    "respec.button.reset_all" = "RESET ALL"
    "respec.dialog.title" = "Confirm reset?"
    "respec.dialog.title.profession" = "Reset {0}?"
    "respec.dialog.title.reset_all" = "Reset all professions?"
    "respec.dialog.cancel" = "Cancel"
    "respec.dialog.confirm" = "Reset"
    "respec.dialog.body.refund_points" = "This will clear every allocated node in {0}. Estimated refund: {1} skill point(s)."
    "respec.dialog.body.refund_one" = "This will clear every allocated node in {0}. Estimated refund: 1 skill point."
    "respec.dialog.body.no_refund" = "This will clear every allocated node in {0}."
    "respec.dialog.body.cost" = "`n`nEstimated cost: {0} (final charge uses actual refunded points)."
    "respec.dialog.body.undo_enabled" = "`n`nYou can press ""Undo"" to restore your previous allocation (and any charged cost) until the game closes."
    "respec.dialog.body.undo_disabled" = "`n`nUndo is disabled in config - this cannot be reversed."
    "respec.dialog.body.reset_all.intro" = "This will reset all profession trees.`n`nEstimated total refund: {0} point(s)."
    "respec.dialog.body.reset_all.cost" = "`nEstimated total cost: {0} (final charge uses actual refunded points)."
    "respec.dialog.body.reset_all.free" = "`nCost: Free"
    "respec.dialog.body.reset_all.undo_per_prof" = "`n`nUndo remains per-profession and will refund each profession's charged cost."
    "respec.dialog.body.reset_all.undo_disabled" = "`n`nUndo is disabled in config - this cannot be reversed."
    "respec.cost.free" = "Free"
    "respec.cost.gold" = "{0:N0} gold"
    "respec.cost.tickets" = "{0:N0} tickets"
    "respec.profession.Combat" = "Combat"
    "respec.profession.Farming" = "Farming"
    "respec.profession.Fishing" = "Fishing"
    "respec.profession.Mining" = "Mining"
    "respec.profession.Exploration" = "Exploration"
}

Write-Host "Bootstrap complete."
