using System;
using BepInEx.Bootstrap;
using HarmonyLib;

namespace CropOptimizer.Integration
{
    internal sealed class TodoIntegration
    {
        private const string PluginGuid = "com.azraelgodking.sunhaventodo";

        public bool IsAvailable =>
            Chainloader.PluginInfos != null &&
            Chainloader.PluginInfos.ContainsKey(PluginGuid);

        public void PublishHarvestReadyTodo(int readyTileCount)
        {
            if (!IsAvailable || readyTileCount <= 0)
                return;

            try
            {
                if (!Chainloader.PluginInfos.TryGetValue(PluginGuid, out var info) || info?.Instance == null)
                    return;

                var pluginType = info.Instance.GetType();
                var getManager = AccessTools.Method(pluginType, "GetTodoManager", Type.EmptyTypes);
                if (getManager == null)
                    return;

                var manager = getManager.Invoke(null, null);
                if (manager == null)
                    return;

                var asm = pluginType.Assembly;
                var prioType = asm.GetType("SunhavenTodo.Data.TodoPriority");
                var catType = asm.GetType("SunhavenTodo.Data.TodoCategory");
                if (prioType == null || catType == null)
                    return;

                var addTodo = AccessTools.Method(manager.GetType(), "AddTodo", new[]
                {
                    typeof(string), typeof(string), prioType, catType
                });
                if (addTodo == null)
                    return;

                addTodo.Invoke(manager, new object[]
                {
                    $"Harvest ready: {readyTileCount} tiles",
                    "Auto-generated by Crop Optimizer",
                    Enum.Parse(prioType, "Normal"),
                    Enum.Parse(catType, "Farming")
                });
            }
            catch (Exception ex)
            {
                Plugin.Log?.LogDebug($"[CropOptimizer] Todo integration: {ex.Message}");
            }
        }
    }
}
