using BepInEx.Logging;

namespace CropOptimizer.Integration
{
    /// <summary>
    /// Thin wrapper around <see cref="SunhavenMods.Shared.TodoSoftClient"/> (AZR-255).
    /// </summary>
    internal sealed class TodoIntegration
    {
        public bool IsAvailable => SunhavenMods.Shared.TodoSoftClient.IsAvailable;

        public void PublishHarvestReadyTodo(int readyTileCount)
        {
            if (readyTileCount <= 0)
                return;

            SunhavenMods.Shared.TodoSoftClient.TryAddTodo(
                $"Harvest ready: {readyTileCount} tiles",
                "Auto-generated by Crop Optimizer",
                "Normal",
                "Farming",
                Plugin.Log);
        }
    }
}
