using BepInEx.Bootstrap;

namespace CropOptimizer.Integration
{
    internal sealed class TodoIntegration
    {
        public bool IsAvailable => Chainloader.PluginInfos.ContainsKey("com.azraelgodking.sunhaventodo");

        public void PublishHarvestReadyTodo(int readyTileCount)
        {
            if (!IsAvailable || readyTileCount <= 0)
                return;

            var todoManager = SunhavenTodo.Plugin.GetTodoManager();
            if (todoManager == null)
                return;

            string title = $"Harvest ready: {readyTileCount} tiles";
            todoManager.AddTodo(title, "Auto-generated by Crop Optimizer", SunhavenTodo.Data.TodoPriority.Normal, SunhavenTodo.Data.TodoCategory.Farming);
        }
    }
}
